### ISSUE TITLE
Add hlsdl as target

### ISSUE THREAD

**Issue by yoshimo** [rowrawer/stream-detector#1]
In some cases https://github.com/selsta/hlsdl works where ffmpeg doesn't so it would be nice if
you could output a commandline for it that includes proper  values

**Comment by rowrawer** [comment]
I haven't heard of hlsdl before, but sure, why not.

**Comment by rowrawer** [comment]
Let me know if it works in v1.7.0.

**Comment by yoshimo** [comment]
Not quite as i expected.

The page itself has two alternative urls for the same video
In the api call to the backend we can get
 hlsURl with an .m3u8 
dashUrl with  a .mpd manifest

The player for my browser seems to choose dash over hls and then the command breaks.
Only the mpd files involved get copied to the clipboard without any application prefix.

Not sure how the bitmovin player decided the protocol that it will use and if we can get the hls tags regardless.

**Comment by rowrawer** [comment]
That's outside of the scope of the addon - it specifically targets the requests your browser does end up making, to ensure maximum compatibility.

That being said, back in the day I used to be able to force different protocols by spoofing the user agent - try changing your user agent to a different browser or even a different OS (Android, iOS).
