### ISSUE TITLE
Add Option to detect

### ISSUE THREAD

**Issue by zackmark29** [rowrawer/stream-detector#10]
Could you please add option which extension to detect?
Like for example. I only need "master.m3u8" and I don't need other m3u8 file

**Comment by rowrawer** [comment]
I'll add it to the to-do list. Something like filtering out the results by filename/type would probably work best for this.

**Comment by rowrawer** [comment]
You can now filter by filename/host as of [v2.0.0](https://github.com/rowrawer/stream-detector/releases/tag/v2.0.0).

**Comment by zackmark29** [comment]
Wow it's amazing! thank you
