### ISSUE TITLE
additional headers

### ISSUE THREAD

**Issue by ukp1992** [rowrawer/stream-detector#100]
Even if the "Include additional headers" option is enabled, only referer and user-agent are output, and additional headers including cookies are not output.
In v2.9.0 and earlier, additional headers can be output without any problem, while v2.10.0 and v2.10.1 have this problem.
The chrome version cannot output the additional header even with v2.9.0.

I would like all request headers except referer and user-agent to be output with additional headers.

Thanks

**Comment by rowrawer** [comment]
Thanks for letting me know. I'll look into it soon.
