### ISSUE TITLE
Can't load the extension on chrome with the recent releases.

### ISSUE THREAD

**Issue by fosam** [rowrawer/stream-detector#101]
Hi!

On Chromium, loading the the extension fails, i noticed this issue with all the releases after 2.9.0, in other words, all releases after this are failing to load when adding the extension to the browser. (using the source code file from releases page)

I'm using Chrome latest version per this day.

<details>
<summary>Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/155383315-6d7a1569-5896-4e17-a730-347942e4fd79.png>
</details>

**Comment by rowrawer** [comment]
Don't use the source code, get the crx file and unpack it.

**Comment by fosam** [comment]
It always worked the source code way, will try to unpack the crx...

**Comment by rowrawer** [comment]
I specifically include the crx file for Chrome users - since 2.10.0 the source code needs to be bundled before use which is why it's not working for you.

**Comment by fosam** [comment]
Worked, but i got "Headers Error" when i extracted the file, no need to worry?

**Comment by rowrawer** [comment]
It should be fine.

**Comment by fosam** [comment]
Thanks!

Quick question, i randomly stumbled upon this [video](https://www.series24hr.com/player/player1.php?id=7497), stream detector coudn't detect the stream there, i'm curious but unfortunately i'm not savvy enough to check it myself, so i thought maybe you would know better than me?

I even tried to grab the stream url from the dev tools but no luck

**Comment by rowrawer** [comment]
At first glance, it seems to be using some sort of proprietary solution involving WebSockets. Pretty neat idea, but would probably be annoying to capture.

**Comment by fosam** [comment]
I see, (BTW i don't need this video, i'm just curious) i tried every "possible" tool to grab this video without luck.

If you get time and are interested in finding a trick to grab it, i would be interested if you let me know, i think it's quite interesting 😁
