### ISSUE TITLE
Clear Filter Button ?

### ISSUE THREAD

**Issue by Mrnofish** [rowrawer/stream-detector#107]
Minor but appreciated QoL improvement: it'd be nice if the filter field had a button to clear it.

Thanks for all the good work on Stream Detector!

**Comment by rowrawer** [comment]
You're absolutely right. I'll add it in the next release.

**Comment by rowrawer** [comment]
This is now available in v2.10.3.

**Comment by Mrnofish** [comment]
Always a pleasure
