### ISSUE TITLE
Doesn't detect Youtube videos

### ISSUE THREAD

**Issue by InfoLibre** [rowrawer/stream-detector#11]
I'm using Firefox 75.0 on Linux Mint MATE 19.3. When I'm looking at a video on Youtube, the Stream Detector icon remain grey, no stream is detected.

![image](https://user-images.githubusercontent.com/3955499/81166351-de413000-8f93-11ea-9c1e-5d2de5a3b0f9.png)

**Comment by rowrawer** [comment]
Already discussed in issue #6. Use regular youtube-dl for mainstream websites, no need to use the addon.

**Comment by InfoLibre** [comment]
Yes, but it's better to use Stream Detector because we have all the youtube-dl options in the command line. For example, with Peertube :
youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0" --referer "https://peertube.fr/videos/watch/e3822d65-f306-4aa9-b9a1-017a5fa19d1e" "https://www.yiny.org/static/streaming-playlists/hls/e3822d65-f306-4aa9-b9a1-017a5fa19d1e/master.m3u8"

**Comment by rowrawer** [comment]
That's true, however these options are simply not required for websites which are fully supported by youtube-dl out of the box. If you specifically need to use any command line options with youtube-dl, you can just type them in yourself, the old-fashioned way.

**Comment by InfoLibre** [comment]
I suppose it's impossible to execute a youtube-dl command directly from Stream Detector ?

**Comment by rowrawer** [comment]
No, of course not, that would be a huge security issue. Why would you want to do that?

**Comment by InfoLibre** [comment]
It would be perfect if we could select a stream in Stream Detector menu and directly record it in a folder. But then Stream Detector should embed youtube-dl.

**Comment by rowrawer** [comment]
That would be pretty cool, but yeah, no mainstream browser would allow this.

**Comment by InfoLibre** [comment]
With https://add0n.com/external-application-button.html , it is possible to send a command to an external application (Terminal...). Would it be possible to do the same with Stream Detector ?

**Comment by rowrawer** [comment]
It is technically possible, but you'd need to install an external application (separately), and that's just not something I'm currently interested in doing.

**Comment by InfoLibre** [comment]
Which installation do I need to install ? In Linux, there's always a terminal and in Windows too. If  Stream Detector detects which system is used, it can send to youtube-dl the good command.

**Comment by rowrawer** [comment]
You don't understand - I'd have to write my own external application to communicate with the addon (which the users would have to download themselves) and then pass on the commands to e.g. youtube-dl. It's definitely possible, and I might implement this at some point, but it's not my main focus.

**Comment by InfoLibre** [comment]
Are you sure ? You don't need to write an external application, like External Application do :

 "External Application Button" adds a single toolbar button plus customizable context menu items to your browser to send page link, selected text, video source, audio source, image source URL to an external application. Using this extension for instance you can open current page in another browser of choice or send image to an external photo editor like GIMP, Paint.net, or even photoshop through context-menu item.

**Comment by rowrawer** [comment]
Have you read through the addon listing?
https://addons.mozilla.org/en-US/firefox/addon/external-application/

> Note that in order for this application to work, there is a minimal native client that needs to be installed manually. Instruction on how to install the minimal client is shown once an application is added to the list. For more info watch the video tutorials or visit add-on's homepage.

What you're describing was possible up to Firefox 56, I think.

**Comment by InfoLibre** [comment]
Indeed, I did not read this part and it seems normal for security reasons.
