### ISSUE TITLE
Replace with Regex

### ISSUE THREAD

**Issue by mortyobnoxious** [rowrawer/stream-detector#110]
Hi, is it possible to have an option to replace title, url or referer etc. with or without regex?

For example on User-Defined Command input, would it be possible to have something like this to replace variables:
`%tabtitle%{watch| }`

![image](https://user-images.githubusercontent.com/42044258/166061972-beb3c958-4d93-4269-b15a-00dafd3d6139.png)

In this case, if tabtitle contains word "watch", it would replace it with an empty string.

[Swift Selection Search](https://github.com/CanisLupus/swift-selection-search)  extension have something like this.

I couldn't find any explanation on their GitHub but these are from extension's options page, if it helps.

![image](https://user-images.githubusercontent.com/42044258/166062112-7a93f39d-056c-454a-95f0-44d460a8ede1.png)
![image](https://user-images.githubusercontent.com/42044258/166062132-824c2b9c-54ec-4c81-a2b6-70590004a641.png)

**Comment by rowrawer** [comment]
Custom syntax would be a pain to implement, but Regex might be doable. I'll think about how to approach this.

**Comment by rowrawer** [comment]
Regex replacement for user command has now been implemented in v2.10.5. Let me know whether it works well enough.

**Comment by mortyobnoxious** [comment]
Thank you, it works great.
