### ISSUE TITLE
Show size preview in pop-up - Noobgamer0111

### ISSUE THREAD

**Issue by Noobgamer0111** [rowrawer/stream-detector#114]
It would be nice if there was a column that could show the expected size of any particular file.

I'm trying to download some uni lectures, but it's hard to determine which is the bigger *.mp4 (so you can find the one with the higher resolution) and I don't want to keep clicking through mp4 links to find that they are low-res videos.

Lecture I'm trying to download: https://echo360.net.au/media/24372b93-6860-404b-b85a-60a933724ac5/public

**Comment by rowrawer** [comment]
This could theoretically be done for direct links to files, but even then lots of files are in tiny segments, so you'd have to manually add them all up. Streamed files would have to get their manifest files downloaded and parsed and even then it's not a guarantee I think. Plus having an addon automatically download a file for itself is a bit iffy. I'd have to think about an approach but I don't think there's any clear way.
