### ISSUE TITLE
Maintain Paused state across browser restarts

### ISSUE THREAD

**Issue by sBrecht** [rowrawer/stream-detector#12]
I love the add on but it would be nice to be able to leave it paused until I want to use it.  When enabled I get pop-ups for detected streams while browsing.  Being able to quickly pause it and have it maintain that state across a browser restart would be greatly helpful.

Thanks!

**Comment by rowrawer** [comment]
Good idea, I'll try to implement this in the next release.

**Comment by rowrawer** [comment]
This should now work as of [v1.11.0](https://github.com/rowrawer/stream-detector/releases/tag/v1.11.0).
