### ISSUE TITLE
Warning in `about:debugging`

### ISSUE THREAD

**Issue by nicolaasjan** [rowrawer/stream-detector#120]
Firefox 101
Linux Mint 20.3

In `about:debugging#/runtime/this-firefox`, I see:
`Reading manifest: Warning processing browser_action.chrome_style: An unexpected property was found in the WebExtension manifest.`

Is this something to worry about?

**Comment by rowrawer** [comment]
No, that's just the byproduct of making an addon that simultaneously works in Firefox and Chrome. Doesn't impact functionality at all. I'll see whether it's still necessary to include these properties in the future.
