### ISSUE TITLE
"Reset Settings" Not working in Chrome.

### ISSUE THREAD

**Issue by fosam** [rowrawer/stream-detector#121]
Dear Developer,

I tried to reset all the settings from the bottom of settings menu, but when i click it, nothing happens, i went to try that on Firefox and there i get a confirmation box where i can click OK, which is something that doesn't appear on Chrome.

Could you check if this is a bug or something similar?

**Comment by rowrawer** [comment]
Google probably broke something in an update, as per usual. I'll look into it.

**Comment by rowrawer** [comment]
This should now be fixed in v2.10.7.

**Comment by fosam** [comment]
The options window is now more visible and full screen, the reset options now is working too!
Thanks!
