### ISSUE TITLE
"Disable search" and "Copy all URLs"

### ISSUE THREAD

**Issue by nkomarov** [rowrawer/stream-detector#122]
Hi! Great plugin, love it.

2 suggestions:

- I find it a bit weird to see the "Disable search" checkbox. It should be reversed - "Enable search" (with reverted logic).
- My use case is always 1) copy URL; 2) paste it somewhere else; 3) don't use the plugin for several hours/days. That's why a button like "Copy URLs and disable search" would be great to have. Maybe not a button but a settings option "Pause search each time URLs are copied to the clipboard".
- I never need more than one URL that's discovered (the newest one). I would prefer to only see this URL and have older URLs disappeared.

Otherwise, it's just great, thanks again!

**Comment by rowrawer** [comment]
Thanks for your feedback.
I'm not sure what you mean by disable search, do you mean the disable detection checkbox? If so, then it makes more sense to me than a checkbox for enabling base functionality. I would assume the default state of an enabled addon would be to have it enabled, with the option to disable parts of it when needed.

As for your other suggestions - they seem to be very specific use cases, so I don't think I'll be implementing any additional functionality for them, but it seems quick enough to copy the URL and then check the disable detection checkbox anyway, and the latest URLs are always at the top. I'd prefer to keep the addon relatively basic and simple.
