### ISSUE TITLE
UX improvements for indicating enabled/disabled state

### ISSUE THREAD

**Issue by ericlee4** [rowrawer/stream-detector#124]
Typically I have this extension set to "disable detection" but sometimes I forget if it's enabled or disabled then when opening a stream I end up unintentionally copying a previous stream with similar enough metadata (filename, timestamp, source, and type). Obviously this is my own fault but perhaps there's a UX improvement we could make to prevent that issue? Instinctively I thought of these changes to show if the extension is active:

1. Change the color of the icon or badge to show the enabled state
2. Display a different badge (number of detections or some string like "disabled")
3. Add background color to the rows on the popup and reduce saturation to indicate the "freshness" of each detected stream
4. Highlight unseen (new since the last time the popup was opened) or uncopied links in the popup

There's probably an infinite number of other UX improvements that could be made but I'm not familiar enough with the extension API to come up with a really good solution. I only want to prevent my issue of opening a stream and then realizing it's one I already copied previously and I need to reload the stream with the extension enabled. Let me know if you like any of these ideas or have your own, I'm more than happy to implement something myself.

EDIT: Thinking about it more: the main issue is that I assume the detection is enabled when it's disabled. Then, when I go to copy the stream link I realize that the stream hasn't been detected and I need to refresh the page to resend the network request so modifying the icon or badge for a hint to the user may be be the best solution if it's possible.

**Comment by rowrawer** [comment]
I get what you're saying. I guess the quickest way to ascertain this at a glance would be to option 1 - having a different color icon when enabled. Could probably be achieved with `browserAction.setIcon()`. New detections already change the badge background color.

**Comment by rowrawer** [comment]
I've added the icon functionality in v2.10.7. Seems to be working fine.

**Comment by fosam** [comment]
@rowrawer Is it possible to have an option to disable old/previous sessions links? sometimes when i click all tabs i see a long list of links that i don't need..

**Comment by rowrawer** [comment]
Links from previous sessions should only appear in their designated tab and not in the all tabs list. I guess I could add a checkbox like "Show only 10 latest entries" or something, to make it more tidy.

**Comment by fosam** [comment]
That would be great, possibly give us the choice to choose like 5 10 15 or unlimited, etc... or maybe even a checkbox to disable the history if possible.

**Comment by ericlee4** [comment]
Wow works great, thanks, I just assumed that you couldn't change the icon dynamically like that.

I'll close this but @fosam you may want to move that idea to a separate issue.
