### ISSUE TITLE
Option to limit/disable links history

### ISSUE THREAD

**Issue by fosam** [rowrawer/stream-detector#126]
Hi!

Is it possible to have an option to disable old/previous sessions links? we discussed this [here](https://github.com/rowrawer/stream-detector/issues/124#issuecomment-1159823349)

A checkbox in the options to clear all URLs/history when closing the tab/browser would be perfect!

**Comment by rowrawer** [comment]
The option to display only a certain number of recent entries is now available in v2.10.8.

URLs from closed tabs and sessions get moved to the all tabs/previous sessions sections respectively.

**Comment by rowrawer** [comment]
I'm not sure why you'd prefer to have less entries than more, but yeah, I suppose there's no need for such restrictions.

**Comment by fosam** [comment]
Just to have more flexibility, on some website i deal with only a couple links and by having the ability to narrow down these links it's more easier and accurate to copy only the desired links at once if you get what i mean.

**Comment by rowrawer** [comment]
I think with only one entry you'd be making it more likely to grab the wrong link, but maybe that's just me.

**Comment by rowrawer** [comment]
The range for the recent entries option is not being limited anymore as of v2.10.9.
