### ISSUE TITLE
Youtube videos and mynoise 

### ISSUE THREAD

**Issue by trimechee** [rowrawer/stream-detector#129]
Hello, thank you very much dor this amazing open-source extension , I searched and I think this is the only media detection extension in the world that is open-source and ad-free !!!

Please i have some question and request : when we put a youtube video, Stream-detector shows us a lot of dash link, we don't know anymore what are the m4a and opus audio links and the valid video links by exp video 360p.....it will be great to add option to simplify downloading youtube video, by exp option to download worst audio format m4a or opus of youtube video, and option to donwload standard quality 360p, or HD qualitiy.....

also when i used stream detector for the first time, there was no url detected, i had to go to options and enable Download video/audio files instead of copying their URLs and Automatically download video/audio files in order that Stream-Detector can detect video links, maybe there is a bug.....

I tried to download this rare sound, with the "Video DownloadHelper" extension, I can download a sound that lasts 30 seconds but with stream-detector, stream-detector cannot detect the url on this site:

https://mynoise.net/NoiseMachines/whiteRainNoiseGenerator.php

**Comment by rowrawer** [comment]
Hello,

As stated in the readme file, there is no reason to use the addon for popular websites such as YouTube. Their methods of delivering content are almost always tweaked in-house. That's not what the addon is for - simply use youtube-dl or yt-dlp directly, as is their intended purpose.

As for the other website - I'll add support for OGG files in an update.

**Comment by trimechee** [comment]
Great !! Thank you very much :)

**Comment by rowrawer** [comment]
OGG files are now supported in v2.10.9.

**Comment by trimechee** [comment]
Great !! Thank you very much :)

**Comment by trimechee** [comment]
Another question please, after adding support of OGG files, i think youtube video has also OGG or opus files dash format but when i tested in the previous days , i only see webm files, is it possibl to add support OGG ou opus files of youtube video please ?

**Comment by rowrawer** [comment]
As stated previously, this addon should not be used with mainstream websites such as YouTube. They are not supported.

**Comment by trimechee** [comment]
Ok, thank you, i ask because i don't like use non open source extension...no problemos, i like use this addon even with mainstream websites, thank you :)
