### ISSUE TITLE
Can not download sproutvideo streams

### ISSUE THREAD

**Issue by gokalper** [rowrawer/stream-detector#13]
Tried all options with headers and all downloaders but I get 403's for the ts files from videostreams that use sproutvideo.com as the source. logs show youtube-dl 

[hls @ 0x7f87e6802000] Failed to open segment 18 of playlist 0
[hls @ 0x7f87e6802000] Opening 'crypto+https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080_00019.ts' for reading
[https @ 0x7f87e66e9600] HTTP error 403 Forbidden
[crypto @ 0x7f87e66e9280] Unable to open resource: https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080_00019.ts

**Comment by gokalper** [comment]
youtube-dl --no-part --restrict-filenames "https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9obHMyLnZpZGVvcy5zcHJvdXR2aWRlby5jb20vYjU3MjRlNjdmOWI1MTcwZjI0MzM2OTVmOThkNTJjZmQvZjk1YjhmMjc3NmJlNDc5MTc5ZDAyYzY1YWJiODZiMzkvKi5tM3U4P3Nlc3Npb25JRD0xNThlNTQzYS1hZDkxLTQ2OTktOWI2MC0xOWRjNDBlZDRiN2YiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1ODk1MTc4NjR9fX1dfQ__&Signature=b1D2WkfJfMvKMWiEOUTu6ZT04xX6F2xdE7duA1Y4vZlV7mf2drgYAu3GwaMgFNmngFwp9wiHlIJ~QwDGeIX7CbS73oQxhjq7ixn5QfvXaWy~1pR-4hw3RwRdmu9cynxhbH4wLpro8UWH24SMhOp7bFS8BsIuSP53fIrHK3hio0hBh976Kz86q9xg8kMa-0h3kQfzUSYCBGRlDnTO9vGRxemhazXnITKwWgeaRpyT4kDuyfA7Ydge5BuoaXW7GEj6eXsz1bIyizarkeM2BE5FCPUfIDGOw7s014BlTN34uN2C4ypI6i7N0lc68S-vzMzUZPS0ZboevOnl44N5EhUOyA__&Key-Pair-Id=APKAIB5DGCGAQJ4GGIUQ&sessionID=158e543a-ad91-4699-9b60-19dc40ed4b7f"
[generic] 1080: Requesting header
[generic] 1080: Downloading m3u8 information
[download] Destination: 1080-1080.mp4
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[hls @ 0x7fcc36000800] Skip ('#EXT-X-VERSION:3')
[hls @ 0x7fcc36000800] Opening 'https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080.key' for reading
^C[hls @ 0x7fcc36000800] Unable to open key file https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080.key
[hls @ 0x7fcc36000800] Opening 'crypto+https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080_00000.ts' for reading
[crypto @ 0x7fcc379a45c0] Unable to open resource: https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080_00000.ts
[hls @ 0x7fcc36000800] Error when loading first segment 'https://hls2.videos.sproutvideo.com/b5724e67f9b5170f2433695f98d52cfd/f95b8f2776be479179d02c65abb86b39/video/1080_00000.ts'

**Comment by rowrawer** [comment]
This looks like an ffmpeg problem related to DRM (or something else) - the addon itself is working as intended.
