### ISSUE TITLE
Does not work as of FF 102.0.1

### ISSUE THREAD

**Issue by mitsukuri** [rowrawer/stream-detector#132]
Zero URLs detected on youtube, bitchute, everywhere else...

**Comment by mitsukuri** [comment]
Ah, I see.. I was under impression that it should have worked there, while it is not guaranteed, per docs. It does work elsewhere. Closing, sorry for the fuss.

**Comment by rowrawer** [comment]
It works fine for me, no difference from 102.0. That being said, there's really no point in using this addon for websites that are natively supported by tools such as yt-dlp.

**Comment by rowrawer** [comment]
Haven't heard of that website before, but it seems to work fine with yt-dlp for me. Might be something on your end.

**Comment by mitsukuri** [comment]
That pretty well may be. Thank you for chiming in!

**Comment by mitsukuri** [comment]
Funny enough, I was able to get the video via devtools/network - it did not stream but rather downloaded the whole video at once at page load. From there, it was no trouble getting it.
