### ISSUE TITLE
Size of video

### ISSUE THREAD

**Issue by trimechee** [rowrawer/stream-detector#133]
Hello, when I go to streaming sites, for the same episode there are several streaming player links, and the size of the videos differ, it will be great if Stream-detector adds an option to show the size of the video because I use the extension to copy the url of the video and paste it in vlc player but I need to know the size of the video to know which video is in HD or SD and which video will be the most fluid when I have a weak login....
Thanks a lot :)

**Comment by rowrawer** [comment]
Hi, thanks for your suggestion. This could only viably be done with direct links to video/audio files, although not always. I'll look into it.

**Comment by trimechee** [comment]
Wonderful !! thank you very much 🥇

**Comment by trimechee** [comment]
and this is the site i use to watch streaming : https://wiflix.bet/vf/16439-stranger-things-saison-1.html

**Comment by rowrawer** [comment]
The size column has now been implemented in v2.10.10.

**Comment by trimechee** [comment]
Woahh ! fantastic ! Thank you very much :)
