### ISSUE TITLE
Scripts to extend download features

### ISSUE THREAD

**Issue by trimechee** [rowrawer/stream-detector#134]
Hello, I discover this awesome and incredible scripts of hoothin, among his scripts, there are these scripts, maybe our beloved Stream-Detector can add these scripts to extend even more other download features, thank you very much !

-DownloadAllContent
Fetch and download main content on current page, provide special support for chinese novel
Script for download novel or text content on page.

Lightweight crawling script, used to download the main text content of the webpage, theoretically suitable for any non-Ajax novel website, forum, etc. without writing any rules for that.

The script will automatically retrieve the main content on the page and download it.

If you are in the novel catalog page, it will traverse all the chapters, sort and save them as a TXT file.

-Easy Offline
Find out all magnet links and torrents and video links in current page, and stream them from cloud storage automatically.

-True URL downloads
Decryption and Display the real URL of the download links and then manage them.(thunder,flashget,qqdl)

https://greasyfork.org/en/scripts/25068-downloadallcontent

https://greasyfork.org/en/scripts/7362-true-url-downloads

https://greasyfork.org/en/scripts/22590-easy-offline

https://github.com/dodying/UserJs/tree/master/novel/novelDownloader

https://greasyfork.org/en/users/8227-hoothin

https://github.com/hoothin/UserScripts

**Comment by rowrawer** [comment]
Hi, thanks for your suggestion. I'm not really interested in implementing new functionalities unless they're deemed necessary - I'd prefer for the addon to be as simple as possible and only do what it's specifically designed to do in order to avoid bloat and bugs.

**Comment by trimechee** [comment]
I understand, thank you :) yes it may be bugs with these scripts but these scripts seems to be popular and widely used and open-source so people have checked the code......may be in the future we will hope an experimental version of the awsome Stream-Detector so that we can avoid installing suspicious non-open-source extensions when we want to download books , pictures....

Thank you again, Stream-Detector is already a magnificent exceptional software ! 🥇

**Comment by trimechee** [comment]
Absolutely !
