### ISSUE TITLE
middle-click toolbar icon to open popup.html in new tab

### ISSUE THREAD

**Issue by mortyobnoxious** [rowrawer/stream-detector#138]
Hi, this is a simple request but if you consider I really appreciate it.

For example middle-clicking **uBlock Origin**'s toolbar icon (as in below) opens "`...popup-fenix.html`" page in new tab.

![image](https://user-images.githubusercontent.com/42044258/184427372-ccca9432-fe84-4dc1-84b9-5ffafa3452cb.png)

It would be nice, if we middle-click "The Stream Detector" and it opens "`...popup.html`" in new tab. (as in below)
![image](https://user-images.githubusercontent.com/42044258/184427180-3e6165e4-fb7b-46b6-8071-e14142a65928.png)

**Comment by rowrawer** [comment]
Sure, good idea.

**Comment by rowrawer** [comment]
This is now available as of v2.10.13.

**Comment by mortyobnoxious** [comment]
Thank you, it's perfect.
