### ISSUE TITLE
Could you add support for sites

### ISSUE THREAD

**Issue by UriF** [rowrawer/stream-detector#139]
I wouldn't like to post these sites here.  How to contact you private?

Thanks

**Comment by rowrawer** [comment]
Sorry, I'm not really keen on adding support for particular sites. The addon aims to support commonly used solutions only. Bothering with proprietary technologies of niche websites would be a headache. If it's not being detected by e.g. yt-dlp, then I surely won't be able to do a better job.

**Comment by UriF** [comment]
Thank you for your response.

I apologize for your inconvenience.
I asked yt-dlp team for javquick but they rejected because this site violate copyright statements.  jDownloader team promised to use a hack to get around javquick restrictions in their new release.  I got this answer in June but they still didn't publish any updates.  By the way they wrote that they work with a new gen of jDownloader(???) where they will be able to to include not just link but also referrer.
As you understand yt-dlp don't have a tool to recognize streams at web sites.  This application just takes a link to stream to try to download.   Therefore (and taking into account copyright issues) I didn't ask them to work with javhdworld.  jDownloader also don't have internal tool to recognize streams.  They just get a link you can take from Video Download Helper which also is not able to recognize this stream.  

I sent request to Ant Downloader and they promised to include these sites into future updates but they didn't update their extension from January, 2022.
Thank you again for taking you time.
Regards,
Uri



    On Sunday, August 14, 2022 at 08:38:07 AM EDT, rowrawer ***@***.***> wrote:  
 
 


Sorry, I'm not really keen on adding support for particular sites. The addon aims to support commonly used solutions only. Bothering with proprietary technologies of niche websites would be a headache. If it's not being detected by e.g. yt-dlp, then I surely won't be able to do a better job.
