### ISSUE TITLE
no cookie header output

### ISSUE THREAD

**Issue by ukp1992** [rowrawer/stream-detector#140]
Hi,

Since v2.10.10, the removal of getting requestHeaders(onBeforeSendHeaders) has resulted in cookie header output is no longer possible.
It is true that set-cookie and content-length are information that can be retrieved by responseHeaders(onHeadersReceived), but However, I would like to fixed this degradation, which prevents the output of cookie headers.

Regards.

**Comment by rowrawer** [comment]
Hi, as stated in your pull request I will consider re-adding that listener in a future release, but implemented better. onHeadersReceived should also carry the necessary cookies.

**Comment by rowrawer** [comment]
I've decided to restore the previous functionality until I find the time to reimplement it in a better way. Everything should be working fine as of v2.10.13.
