### ISSUE TITLE
No streams detected

### ISSUE THREAD

**Issue by Cultura-Difusa** [rowrawer/stream-detector#145]
Hello there,

I do not know if it is something at my end, but **_no streams_** are found with the extensions.

If I can send you any debug data that you might need, please tell me how, and I would gladly do.

 [firefox 103.0.2 / Arch] _**Extensions**_: 

1. Facebook Container
2. Multi-account container
3. Gnome Shell integration
4. Https everywhere
5. uBlock Origin
6. Zotero connector
7. **_Stream detector_**

Thanks for your work, your "add-on" is extremely useful, and saves time.

**Comment by rowrawer** [comment]
Hi, thanks for your report. I don't really do debug data as that's too much of a bother. Try to launch Firefox with only Stream Detector enabled (all other extensions disabled). Then reset data in the options if it still doesn't work maybe.

**Comment by Cultura-Difusa** [comment]
I'll have a look and keep you posted. Thanks.
