### ISSUE TITLE
Palemoon Browser

### ISSUE THREAD

**Issue by trimechee** [rowrawer/stream-detector#147]
Hello, I recently installed Pale moon browser and I discovered some options not present in mainstream browsers, for example I can disable MSE media source extension and buffer full video in some streaming websites, and it use less memory... .

I spoke with the palemoon team about suggestions and improvements but i get a little argument with one of the maintainers when I said something about ad blockers lol.....and I was banned from the forum for a few days lol, so I don't like to make my request to their forum anymore, that's why I'm posting my request here, it will be great if our beloved Stream-Detector adds an extension for pale moon, there is a manager in charge of adapting firefox addons for palemonn but unfortunately I no longer wish to express myself in the palemoon forum after this misunderstanding.....

Thank you very much :)

https://forum.palemoon.org/

**Comment by rowrawer** [comment]
Sorry, I only support the latest available version of Firefox. Too much of a headache to support anything else - but it might still work on forks of course.

**Comment by trimechee** [comment]
Ok, there is no problem, the idea is to let pale moon team adapt stream setector like downthem all, and may be you bring them technical advice or expertise.....i understand, there is no problem :) i used downt them all extension in pale moon but i can't copy url quiclly that's why i request that..... there is no problem, thank you again for this wondrtful extension 🥇
