### ISSUE TITLE
HLS

### ISSUE THREAD

**Issue by trimechee** [rowrawer/stream-detector#148]
Hello, many and many video and streaming sites use HLS m3u8, it will be great to make our beloved Stream-Detector even more powerful by adding support  download  of HLS streams, these ope source extensions to download crypted HLS streams may help may be, thank you very much !

https://github.com/chandler-stimson/live-stream-downloader

https://github.com/zaidka/cliget

https://github.com/globocom/m3u8

https://github.com/HeiSir2014/M3U8-Downloader

https://github.com/hestyle/m3u8_downloader

https://github.com/kz26/gohls

https://github.com/Last-Order/Minyami

https://github.com/Momo707577045/m3u8-downloader

https://github.com/Momo707577045/media-source-extract

https://github.com/nilaoda/N_m3u8DL-RE

https://github.com/puemos/hls-downloader

https://github.com/Spark-NF/hls-downloader

https://chrome.google.com/webstore/detail/m3u8-finder-and-hls-playe/gijhpnmjcpbddpedmmdihijogkkejfgj?hl=en

https://www.hlsloader.com/

https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by rowrawer** [comment]
I'm not entirely sure what you mean, as Stream Detector already supports HLS streams. It was, in fact, its very first feature.

**Comment by trimechee** [comment]
Wouahh, I didn't know that, I'm very impressed !!Stream detector can merge video and audio files automatically and decrypt the crypted protected streams ?

**Comment by trimechee** [comment]
Oups , sorry, now i am reading the description of Stream detector ,  i see it can detect HLS streams, that's cool ! i uses to use the extension just to donwload mp4 streams, sorry :)
