### ISSUE TITLE
Standalone features

### ISSUE THREAD

**Issue by jaylex32** [rowrawer/stream-detector#149]
Can you please make this tool as a command line tool so it can be modified and be added with yt-dlp as a script?

thanks in advance!

**Comment by rowrawer** [comment]
How would it detect URLs if it's not in the browser?

**Comment by jaylex32** [comment]
> How would it detect URLs if it's not in the browser?

There’s no way to do it with Uri web request method?

**Comment by rowrawer** [comment]
I'm not sure what you mean. Uri web request method in the command line? Can you provide an example?

**Comment by rowrawer** [comment]
I'm not particularly familiar with Powershell commands, but it seems like that just downloads the URI into a file. The script detects things a bit more differently and relies on browser requests.

**Comment by jaylex32** [comment]
Thanks
