### ISSUE TITLE
Microsoft store

### ISSUE THREAD

**Issue by trimechee** [rowrawer/stream-detector#152]
Hello, the amazing Stream-Detector worked in chromium browser like Thorium browser, ungoogled chromium....

and I tried to install Stream-Detector on Edge browser but edge removes the extension because it is not in the microsoft sotre, in case there will be censorship on firefox, or to be able to try stream detector with edge browser, is it possible to add stream detector in the microsoft store please? 

or add it in the chrome store because edge browser can download extensions from chrome store? or add Stream-Detector in the opera store, because I found an extension that allows you to install opera extensions on chrome and chromium browsers please?

https://chrome.google.com/webstore/detail/crosspilot/migomhggnppjdijnfkiimcpjgnhmnale/related

i tried with crosspilot sandbox extension installed in edge browser, but even with this extension, i fail to install stream detector :(

i have this message from crosspilot:
"clipboardWrite (Unsupported)
Notifications (Unsupported)
webRequest (Unsupported)"

**Comment by rowrawer** [comment]
No, sorry, this is a Firefox addon. It is unlikely I will support Chrome in the future due to their plans of enforcing manifest v3 in the near future.
