### ISSUE TITLE
why not to display or select the video quality in The Stream Detector?

### ISSUE THREAD

**Issue by candrapersada** [rowrawer/stream-detector#156]
![image](https://user-images.githubusercontent.com/36833664/199723444-cf6ab959-ee18-401b-8157-8b35c1b2f914.png)

**Comment by rowrawer** [comment]
I've already explained this, but this would involve downloading and parsing every manifest file in the background, and I'd prefer the addon to be relatively minimalistic and not do to much behind the user's back. As it stands, the addon only analyzes existing traffic.
