### ISSUE TITLE
Error with Chrome

### ISSUE THREAD

**Issue by MaZED-UP** [rowrawer/stream-detector#159]
`CRX_REQUIRED_PROOF_MISSING`
This error appears to me when I try to install the extension on my Google Chrome browser Version 107.0.5304.87 (Official Build) (64-bit).
I found this in [Stackoverflow](https://stackoverflow.com/questions/56930454/chrome-extension-throws-crx-file-error-crx-requird-proof-missing):
"In recent versions of Chrome only CRX3 format is supported"

**Comment by rowrawer** [comment]
Sorry, Chrome is not supported. The best solution would be to use Firefox instead. Or unpack the crx file and use the `Load unpacked` option in `chrome://extensions`.
