### ISSUE TITLE
Feature request, option to share link

### ISSUE THREAD

**Issue by Sovilor** [rowrawer/stream-detector#161]
Android Firefox nightly, Fennec F-Droid.
Hello, please add option to share a selected link, so we can play the file with app we choose.

Thank you.

**Comment by Sovilor** [comment]
@rowrawer Hello, sorry for my late answer and excuse my English, 
It looks like I'm the first Android user for your addon :) 
I will gladly help in testing if you needed.

![Screenshot_2022-11-23-04-30-22-481_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/48744665/203464594-2055b2ce-bd8f-41be-ade3-1ceb5c2ef861.jpg)
This is a screen shot of what i get on Android Firefox.
(can't you just copy as URL?) Yes when i click on a link it will be copied.
But as you see in the screen shot, the size is not showing, and the full link of the video is not showing, so it's impossible to know the quality.
So if we have an option to view the full link of the video that will be very helpful.

Back to the main point (Feature request), 
The idea is simply to have a button called (share the selected link) or called (play selected link) or (open selected link) to be able to play a selected link with external App like MX Player or VLC for Android directly.

Thanks for your effort.

**Comment by rowrawer** [comment]
I get what you mean. Adding another button doesn't seem ideal as there's already enough buttons there. I'll have to think of a way to display the full filename.

**Comment by rowrawer** [comment]
The filenames will now be displayed in full (possibly in multiple lines) in v2.10.19, hopefully for better clarity.
