### ISSUE TITLE
How can I pay you for this excellent software

### ISSUE THREAD

**Issue by Vaultmanager** [rowrawer/stream-detector#167]
Please provide some method for satisfied users to be able to pay you for this excellent software. I have been using it for several years by now and it helped me a lot. Thank you.

**Comment by rowrawer** [comment]
Hi, thanks for your offer. This addon has always been 100% free in every way, but I will consider setting up an account at some sort of donation platform.

**Comment by rowrawer** [comment]
This is now available here: https://github.com/sponsors/rowrawer
Haven't tested it yet, but we'll see how it goes.

**Comment by rowrawer** [comment]
Decided to remove this option - not really aligned with the spirit of the addon and the work I do here.
