### ISSUE TITLE
Toolbar icon shows a total number of finds that keeps increasing

### ISSUE THREAD

**Issue by cipricus** [rowrawer/stream-detector#168]
![image](https://user-images.githubusercontent.com/3447868/208890765-84b3c577-6931-4f9b-9f02-da89eec5c9a6.png)

I think the expected behavior is that the toolbar icon displays the number of streams found and listed at the present moment, but what I see is an increasing number that I guess is that of the total streams found since the installation of the extension.

**Comment by rowrawer** [comment]
The number should reset on browser shutdown. Does it persist through launches?

**Comment by cipricus** [comment]
> The number should reset on browser shutdown. Does it persist through launches?

Oh, I'm very sorry. I thought I had even rebooted. But no, you are right, simply restarting the browser is enough.
