### ISSUE TITLE
Page needs multiple refreshes for ALL streams to show with the new interface..

### ISSUE THREAD

**Issue by SNAPflix** [rowrawer/stream-detector#17]
Hi! 
First of, I LOVE this extension.. So THANK YOU for creating it..! BUT...

Since you changed the interface the extension now often only show SOME of the streams.
I use it to find both video AND vtt subtitles on the webpage, but often it only show 1 or a few but NOT all available subtitles. UNLESS I refresh the page multiple times.
Sometimes I even have to use "Live http headers" to find the subtitle I want since your extension refuses to find the one I am looking for..

Before you changed to the new interface it ALWAYS found ALL streams..
I hope you can fix this issue. Otherwise I will need to revert to one of your old versions.

Please keep up the good work you are doing, it's MUCH appreciated!

**Comment by rowrawer** [comment]
Hello,

The detection algorithm has remained mostly unchanged since the previous version, it works exactly the same as it used to for me. Can you provide specific URLs where this happens? I can't really verify and test this without any examples.

**Comment by SNAPflix** [comment]
Thanks for replying! 
The website I refer to is this one: [NyaFilmer](http://nyafilmer.lol/home) which provides videos and subtitles for all Nordic languages, but also English in some cases.

Here is 2 screenshots as example. It SHOULD list VTT files in 4 languages but inly Finnish (Suomi) comes up...

![Example-2](https://user-images.githubusercontent.com/10277805/84184290-5ddb8680-aa8d-11ea-89df-4df316774fb0.png)


![example](https://user-images.githubusercontent.com/10277805/84183654-86af4c00-aa8c-11ea-8079-2c1fa9739525.png)


I never had ANY issues until the change of the interface of the extension. That's why I wrote to you.
THANKS for taking your time to look into this..!

**Comment by rowrawer** [comment]
Thanks for clarifying. I see where the bug is. I'll do my best to fix it in the next version.

**Comment by SNAPflix** [comment]
Thanks AGAIN! 
Looking forward to it..  :smile:

**Comment by SNAPflix** [comment]
I just tested it and you'll get 2 thumbs up from here...  :+1: :+1:
You solved this issue and I'll close it...
Thanks again!
