### ISSUE TITLE
Feature request: the toolbar button number should change to reflect the number of listed streams

### ISSUE THREAD

**Issue by cipricus** [rowrawer/stream-detector#171]
This is the most powerful tool of its kind in my experience. Thank you for it!

But I'm bothered by a problem -- a relatively small one, but one that gives a false impression about the quality of this addon, which deserves better:

Even with no stream detected and listed, a huge number is listed on the button, which is misleading. 

I know that number  is reset upon browser restart, but it quickly gets huge without obvious reason. Huge or low, as long as it doesn't reflect the number of finds (what other expected behavior can there be?), maybe it shouldn't be there at all:

![image](https://user-images.githubusercontent.com/3447868/210768325-8954c746-0298-41ab-a083-fd8d5e1a7ffb.png)

What is that number in fact? The history of all streams ever found since opening the browser? (That would be unexpected, if the setting is to show only what is found in selected tab, and not other sessions.) How can that number be used?

**Comment by rowrawer** [comment]
It's the total number of detections per browser session. Initially it used to reset upon opening the popup menu, but it was changed due to user request I believe. I might revert this behavior and change it to some sort of symbol instead of a number, but I'm not sure. It's not particularly high on my list of priorities, as most of the time I forget that number is even there.

**Comment by cipricus** [comment]
The number would be great if it showed the listed streams, based on the settings seen in image above to have the list for selected tab, for all tabs or for ...  session (? _present_ session would have made more sense than _previous_, and would have corresponded to the present behavior).

> I forget that number is even there.

Well, one has little choice but to try to ignore it :)

**Comment by cipricus** [comment]
Testing more, I realize that the number I see is the number of streams listed if I select the "All tabs" option!

![image](https://user-images.githubusercontent.com/3447868/210980925-db3e2ebe-c602-49df-b574-8678cadf0939.png)

As simple as that.

So the feature request should be: button number should be based on the selected setting!

**Comment by cipricus** [comment]
> It's the total number of detections per browser session

_It's also the number of streams listed if we select "All tabs" in the image above_, although they stay listed even if the tabs are closed. 

This makes the setting "All tabs" a bit misleading too. It should be called "Present session", as it is not about open tabs, but about all tabs opened or closed during present session. 

No matter the name of that setting, that's what the present number shows: the number of stream listed if we select "All tabs".

**Comment by rowrawer** [comment]
>It's also the number of streams listed if we select "All tabs" in the image above -- although they stay listed even if the tabs are closed, which makes the setting "All tabs" a bit misleading too: it should rather be called "Present session"

I suppose so. I'll rename the option.

>But it would be great if the number reflected the list we see when we click the button. - I have updated the title accordingly. We should be able to change that number in the same way we can change the list.

I don't see why you'd need it to have any intricate functionality - it's just there to show that something's being detected, the number itself never really mattered. If it was restricted to only the current tab,  you might miss detections in other tabs. I guess I could implement an option to choose one's preferred functionality of this number, but, again, that's not particularly high on the list of priorities.

**Comment by cipricus** [comment]
> I don't see why you'd need it to have any intricate functionality ... 

No intricacy sought here, it's just that the number is there and one simply expects that when clicking it one sees the items to which the number seems to refer.

> the number itself never really mattered.

My request is that can be made to matter 

< ...I guess I could implement an option to choose one's preferred functionality of this number

Make the button number read from the list which is there anyway: the option to choose what the list includes is there already: just make the number reflect the list

**Comment by rowrawer** [comment]
>No intricacy sought here, it's just that the number is there and one simply expects that when clicking it one sees the items to which the number seems to refer.

That's only what you personally expect. I'd expect the number to represent the total number of detections per session, which is what it does now.

>Make the button number read from the list which is there anyway: the option to choose what the list includes is there already: just make the number reflect the list

This would be quite annoying to implement, as the list is only generated once the popup menu is opened. But I'll consider this possibility if I decide to change the behavior of the number. Although, if anything, I'll probably replace it with something more general, like an exclamation mark or something.

**Comment by cipricus** [comment]
> quite annoying to implement, as the list is only generated once the popup menu is opened.

That is far above my competence, and serves as a response to my request, so you could close this if you so please.

> That's only what you personally expect. I'd expect the number to represent the total number of detections per session, which is what it does now.

I am sorry if I have somewhat let the impression that I wanted to challenge your intentions. My impression is that feature requests are meant to reflect the expectations of the users, and that is why I have tried to fathom and express here. My expectation can only be personal and should not be judged in contrast to intentions of the creator. My  own is framed by experience with other popular tools (like video download helper and others) where any number listed serves a purpose as the one I have tried to define. I think that is expected, intelligent behavior which serves well both the user and the addon's popularity.

I find your addon so good I simply regret it's not the most popular out there (so I've tried to think how it can be improved: I do have a lot of experience of a user and you can trust my good intentions). All the best to you!

**Comment by rowrawer** [comment]
>I am sorry if I have somewhat let the impression that I wanted to challenge your intentions.

No need to worry. I appreciate all feedback and take it into consideration. Popularity does not concern me much, as this is not a commercial product - ultimately it's just a tool I made for personal use which other people have also found useful. Thanks for the kind words.

**Comment by cipricus** [comment]
> Popularity does not concern me much

Maybe you are right, but I tend to see things as follows: the more popular a non-commercial, open-source tool is, the bigger are the chances that new developers take over a project when technologies change and the tool stops working. I am not a developer, and I'm not sure how things really work though, but that's what I'd like to see, and maybe we don't see it often enough.

**Comment by cipricus** [comment]
> I'd expect the number to represent the total number of detections per session

When that happens (and it happens all the time) one would expect _to see and access_ those detections: but that _only_ happens if "All tabs"  is the selected option. Otherwise, we see much less than that number, or nothing at all, or much more entries (from all sessions, which is far too much!)

**Comment by rowrawer** [comment]
The toolbar badge now counts the amount of detections since the popup was last opened.
