### ISSUE TITLE
Not bulelive sport stream

### ISSUE THREAD

**Issue by wlsstn1** [rowrawer/stream-detector#174]
Streaming sites such as bulelive or tvchak.com give fake api. I can't get the real address.

**Comment by rowrawer** [comment]
Any specific examples? I can't seem to find the address for bulelive and tvchak is geolocked.

**Comment by wlsstn1** [comment]
네이버 메일 앱에서 보냈습니다.
날짜: 2023.01.10 오후 09:46:35 (GMT+09:00)
제목: Re: [rowrawer/stream-detector] Not bulelive sport stream (Issue #174)

Any specific examples? I can't seem to find the address for bulelive and tvchak is geolocked.

**Comment by wlsstn1** [comment]
tvchak.com, you will know.


네이버 메일 앱에서 보냈습니다.
날짜: 2023.01.10 오후 09:46:35 (GMT+09:00)
제목: Re: [rowrawer/stream-detector] Not bulelive sport stream (Issue #174)

Any specific examples? I can't seem to find the address for bulelive and tvchak is geolocked.

**Comment by wlsstn1** [comment]
Then is it not possible because this is Korea? Can I bypass the vpn?

**Comment by wlsstn1** [comment]
By bypassing the vpn, it appears that it can only be viewed in Korea. If stream detect m3u8 is detected, the phrase 403 Forbidden appears.

**Comment by rowrawer** [comment]
It's hard for me to diagnose the issue since I can't directly access the websites you mention. Maybe the streams use DRM or need cookies to function. Copying URLs as ffmpeg or yt-dlp commands could help with that.

**Comment by wlsstn1** [comment]
네이버 메일 앱에서 보냈습니다.
날짜: 2023.01.12 오전 01:41:12 (GMT+09:00)
제목: Re: [rowrawer/stream-detector] Not bulelive sport stream (Issue #174)

It's hard for me to diagnose the issue since I can't directly access the websites you mention. Maybe the streams use DRM or need cookies to function. Copying URLs as ffmpeg or yt-dlp commands could help with that.
