### ISSUE TITLE
Do not see wideo

### ISSUE THREAD

**Issue by DajMiliona** [rowrawer/stream-detector#175]
Please add support for
https://joemonster.org/filmy/
https://www.sadistic.pl/
https://demotywatory.pl/filmy
https://www.polsatnews.pl/wideo-lista/
https://www.polsatnews.pl/wideo/sulechow-18-latek-przejechal-przez-srodek-ronda-nie-uniknal-kary_6814963/?ref=article
https://fakty.tvn24.pl/
https://kwejk.pl/kategoria/filmiki

**Comment by rowrawer** [comment]
The addon does not support individual websites, only particular protocols and technologies as a whole I see no reason why these shouldn't work unless they use proprietary, in-house methods.

PS. Odznacz "Nie wykrywaj bezpośrednich linków do multimediów" w opcjach, ew. użyj yt-dlp bezpośrednio, nie powinno być kłopotu.

**Comment by DajMiliona** [comment]
Cos pieknego :) Teraz złoto :)
Dlaczego wykrywa mi 3 razy stream wideo na Polsacie? 
https://www.polsatnews.pl/wideo/niemcy-starcia-aktywistow-klimatyczni-z-policja-spor-o-kopalnie-wegla-brunatnego_6815050/?ref=wideo_top_najnowsze

Czy idzie zrobić wykrywanie strumieni radiowych? RMF Zet oraz kazdego innego?

**Comment by rowrawer** [comment]
Wykrywa 3 razy, bo wszystkie 3 linki są używane, przekierowują po kolei do ostatniego.

Co do strumieni radiowych - nie mam zbytnio doświadczenia z polskimi stacjami radiowymi, ale podejrzewam, że wystarczyłoby ręcznie podejrzeć z jakiego URLa streamują audio (choćby pod F12 w przeglądarce), a potem dodać jakiś charakterystyczny fragment tego linka do listy "Wykrywaj dodatkowe rozszerzenia plików" w opcjach. Potem powinno wykrywać automatycznie.

**Comment by DajMiliona** [comment]
Czy możes jakiej z tymi linkami? Kazdy jeden kopiowałem i wklejałem w osobną kartę. Zapisywałem filmy i sprawdzałem czy te same parametry filmu sa. Ewentualnie opcja,. aby ukrywać powtarzające sie linki? 
Co do radia to ja sie nie znam na kodzie, i nie wiem jak prawidłowo pozyskiwać. Wiem, że ludzie jakoś znajdowali linki do stacji RMF. Była jedna domena, Jak sie w winampa wrzuciło to pod ta domeną było mase adresów np 1 nie działa leci na kolejny i tak dalej. Przykład ![Radio_RMF](https://user-images.githubusercontent.com/39501742/212070930-6853671f-f815-448f-8634-de87cebeaa92.png)
https://www.rmfon.pl/play,5#p
W jaki sposób, któś wiedział, ze strumień jest pod takim adresem zachodze w głowe od wielu lat :)
Przykład w załączniku. Adres z playlistą adresów (domena czy jak to sie tam nazywa).
Jak taki adres pozyskac :)

**Comment by rowrawer** [comment]
Wszystkie linki wykrywane na tej stronie przekierowują do pliku wideo, po prostu przechodzi przez kilka adresów, dlatego jest wykrywany wielokrotnie. Logicznie rzecz biorąc wystarczy skopiować ten najpóźniej wykryty (wyżej na liście), o ile nazwa pliku jest taka sama. Linki same w sobie się nie powtarzają, po prostu prowadzą do tego samego miejsca. Tego typu duplikacji addon nie wykrywa, bo byłoby to trochę zbyt inwazyjne i mogłoby przypadkowo filtrować funkcjonalne linki.

Co do RMF, to na pierwszy rzut oka widzę, że link jest taki: https://rs101-krk-cyfronet.rmfstream.pl/RMFFM48?aw_0_req.gdpr=false&aw_0_req.userConsentV2=&aw_0_1st.playerid=RMF_Player_JS_P&aw_0_1st.rmf_disable_preroll=true

Otwierasz nową zakładkę, włączasz developer tools pod F12, zakładka network i tam po załadowaniu strony będzie widoczny m.in. ten link. Da się zgadnąć po frazie "rmfstream" i rodzaju linka "media" :) W opcjach addonu dodajesz do listy dodatkowych rozszerzeń np. "RMFFM48" albo właśnie "rmfstream" i przy następnym załadowaniu strony powinno już wykryć.

**Comment by DajMiliona** [comment]
Nie chce Ci głowy suszyć radiem.
Nie wkleiło mi poprzednio linku: http://www.rmfon.pl/n/rmffm.pls <--- o znajdywanie czegoś takiego mi chodzi. Ja wiem, dla pozostałych moge dane podmienić, ale jak w stronie odszukac ten adres. On zawiera playliste adresów.

**Comment by rowrawer** [comment]
Takich linków addonem raczej nie znajdziesz, bo nie są używane w odtwarzaczach streamingowych. To są playlisty z dawnych czasów, być może wciąż udostępniane gdzieś w celu kompatybilności ze starym sprzętem - tak przynajmniej przypuszczam.
