### ISSUE TITLE
[Request] Sidebar Support

### ISSUE THREAD

**Issue by zero77** [rowrawer/stream-detector#176]
Can you please add support for opening stream detector in the firefox side bar, as it would make it easier to view when there's lots of streams on one page.

**Comment by rowrawer** [comment]
Never really considered it before but I'll look into it and check if it's viable.

**Comment by zero77** [comment]
> Never really considered it before but I'll look into it and check if it's viable.

I am not sure how its done but, uBlock Origin supports it and the below may help:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action

**Comment by rowrawer** [comment]
The sidebar is now available in v2.11.0.

**Comment by zero77** [comment]
This looks really good thanks.
