### ISSUE TITLE
Is it possible for tvchak.com to export an address called azure?

### ISSUE THREAD

**Issue by wlsstn1** [rowrawer/stream-detector#177]
The address is distributed in the microsoft cloud. Is this m3u8 extractable?

**Comment by rowrawer** [comment]
I have no clue, sorry. I'm not familiar with this website. You'd have to check yourself. Theoretically every m3u8 URL can be extractable.

**Comment by wlsstn1** [comment]
네이버 메일 앱에서 보냈습니다.
날짜: 2023.01.15 오후 10:07:23 (GMT+09:00)
제목: Re: [rowrawer/stream-detector] Is it possible for tvchak.com to export an address called azure? (Issue #177)

I have no clue, sorry. I'm not familiar with this website. You'd have to check yourself. Theoretically every m3u8 URL can be extractable.

**Comment by rowrawer** [comment]
I've seen you reply to issues with your email - just letting you know I can't actually see your responses this way for some reason. It'd be better if you used the website directly.

**Comment by wlsstn1** [comment]
Thank you for your kind reply.

**Comment by wlsstn1** [comment]
날짜: 2023.03.02 오전 00:40:55 (GMT+09:00)
제목: Re: [rowrawer/stream-detector] Is it possible for tvchak.com to export an address called azure? (Issue #177)

Closed #177 as completed.

**Comment by rowrawer** [comment]
Again, GitHub seems to be cutting off your email response.
