### ISSUE TITLE
Komenda otwórz wideo z Facebook w VLC

### ISSUE THREAD

**Issue by DajMiliona** [rowrawer/stream-detector#178]
Czy jest mozliwe, aby live video z transmisji na facebook szło oglądać w VLC w bardzo dobrej jakości? Jest jakies polecenie, którego można uzywac? Cos poprzez stramlink lub inne programy, aby sie player VLC otwarł. Obecnie odtwarza ale w najgorszej jakości i nie idzie nic zrobić, aby ogladać w najlepszej.

**Comment by rowrawer** [comment]
Z osobistego doświadczenia to nie mam pojęcia, bo nie używam Facebooka ani VLC. Addon nie jest pisany pod takie zastosowania. Z readme:

> Websites such as YouTube, Vimeo, Facebook, etc. are very likely to use proprietary technologies which are not supported by this addon. When it comes to such "mainstream" services, it's better to use the tools (e.g. yt-dlp) directly.

Spróbuj może zrobić pipe z outputu yt-dlp do VLC w linii komend:
`yt-dlp -f best LINK -o - | vlc -`

Na przyszłość prosiłbym o sprawy związane stricte z addonem, najlepiej po angielsku, aby wszyscy mogli zrozumieć.
