### ISSUE TITLE
N_m3u8DL-RE referer not working for windows

### ISSUE THREAD

**Issue by candrapersada** [rowrawer/stream-detector#179]
why N_m3u8DL-RE referer not working for windows in The Stream Detector v2.10.19 
`|`
```
N_m3u8DL-RE "https://hive.gdriveplayer.link/PfRxjbPdBRcWxO__0FwIYDh5PgqStcOI3MwmPO9ATcv05KxfkuXxpiTn-gRh3AIfUWY3lePRZe3tDdRg_A22Lg/5c3WmHuXbxQqC8ApIqT9Gf9h34xVPY8KonisKaL99sA/video.m3u8" --header "User-Agent: Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64%3B%20rv%3A102.0)%20Gecko%2F20100101%20Firefox%2F102.0|Referer: https%3A%2F%2Fgdriveplayer.link%2F" --save-name "video"
```

**Comment by rowrawer** [comment]
This should now be fixed as of v2.11.0.

**Comment by candrapersada** [comment]
why Referrer `N_m3u8DL-RE` like this  `"Referer: https%3A%2F%2Fgdriveplayer.link%2F"` not like this  `"Referer: https://vidstream.pro/"`

**Comment by rowrawer** [comment]
This was implemented due to the way cookies used to be passed to the tool. Nowadays I think they can be copied as they are, so there's no need for the headers to be encoded. I'll change that in the next version.

**Comment by rowrawer** [comment]
Referrer is not being encoded anymore as of v2.11.1.
