### ISSUE TITLE
[Question] Copy stream URL as:

### ISSUE THREAD

**Issue by fosam** [rowrawer/stream-detector#180]
Hi

What does this option actually do? i tried the first 8 items in the drop-down menu, but the copied link is the exact same one.

How do i make use of this option? is there something that needs to be configured before using this option?

**Comment by rowrawer** [comment]
No, it should work out of the box with any supported filetype (e.g. M3U8). It works just fine for me, but when testing, I sometimes forget to copy the link again after choosing a different option and think I've broken it, so make sure you're doing that, or maybe try resetting the options. Otherwise I'm not sure why it wouldn't work for you.

**Comment by fosam** [comment]
Ah, i see what can be the issue, my link is not an M3U8, it's rather an FLV, maybe the readymade commands are not supported when dealing with FLV?

**Comment by rowrawer** [comment]
I don't remember off the top of my head, but custom file extensions etc. might only work with regular URL and custom command copying as there's not guarantee they would work with any of the tools (because they're custom).

**Comment by fosam** [comment]
According to the test i did with the flv link, i think you are right, only the regular link is copied.

BTW, copying a url as yt-dlp for example, i unchecked most of the options in the settings and the copied link looks like this:

`yt-dlp --no-part --restrict-filenames "link"`

I would like to achieve this result (Just the basic command+link)

`yt-dlp "link"`

Any tips?

**Comment by rowrawer** [comment]
Use a custom command.

**Comment by fosam** [comment]
This is great, i haven't paid enough attention that custom commands were made for this purpose.

Thanks!

**Comment by fosam** [comment]
@rowrawer Sorry that i have a last question..

Any idea how to copy only a part of a stream link?

<pre>
e.g. <b>https://xxx.xxxxxx.net/xxx/xxx/720/playlist.m3u8</b>?xxxxxxxxx1&ccf=16&dt=pc
</pre>

In other words, copy only the bold text.

Sometimes it's a pain in the rear if you're only after parts of the link.

**Comment by rowrawer** [comment]
That's not something you can do with the addon, sorry. Too specific of a use case.

**Comment by rowrawer** [comment]
Theoretically yes, but I'm not planning on doing it - too much work for something I would never use.

**Comment by fosam** [comment]
Alright, btw, have you ever not encountered a case where you only need the part before `?` or `&` of a link? i see that in some cases it's becoming a thing.

**Comment by rowrawer** [comment]
Not really, no. But I would just do it by hand if I had to anyway, or maybe write a Python script for it if I had an entire batch.
