### ISSUE TITLE
.vtt doesn't work with copy stream as .... command

### ISSUE THREAD

**Issue by cjrayance** [rowrawer/stream-detector#183]
Hello, sir 

when i detected .vtt i want to copy stream as ... command to download with filename 

but when i try to do this, just copy url of .vtt not like a command 

What additional settings do I need?

![2023-02-16 00-57-33](https://user-images.githubusercontent.com/122617363/219114003-b661259c-423a-48ea-ab5f-69a946beb560.gif)

thanks

**Comment by rowrawer** [comment]
I think subtitles currently default to being copied as URLs. Would there be any point to copying them as yt-dlp commands?

**Comment by cjrayance** [comment]
because i want a filename format from your options and yt-dlp work for this site

**Comment by rowrawer** [comment]
What do you mean by filename format? Couldn't you use a custom command for this?

**Comment by cjrayance** [comment]
![Screenshot 2023-02-16 011148](https://user-images.githubusercontent.com/122617363/219116540-7885f91c-971e-4257-b077-856ccac5b5cd.png)
i use this to get a filename format

**Comment by rowrawer** [comment]
So you use yt-dlp to essentially rename the file?

**Comment by rowrawer** [comment]
Maybe try a user-defined command like `yt-dlp -o "%tabtitle%.vtt" %url%`. I'll enable support for subtitles in the tools in a future release, as it's a bit of an outdated restriction.

**Comment by cjrayance** [comment]
thank you sir, It works very well 
`yt-dlp -o "ดูซีรีส์ เกียรติยศหน่วยรบพิเศษ Glory of Special Forces (2022) พากย์ไทย EP 1-0.vtt" https://stream-dn.monomax.me/streams/20220510/tCeZSY5HWmCe5agY/b85Bi24QiEJTJfbt.vtt`
![111](https://user-images.githubusercontent.com/122617363/219120236-a0999545-c4c0-4771-8a08-3281a240c7fe.png)

**Comment by cjrayance** [comment]
By the way, can you share an example of custom command for query filename ? 
and Where do I go to read about this topic?

**Comment by cjrayance** [comment]
i really don't know where %tabtitle% come from

**Comment by rowrawer** [comment]
Addon options -> mouse over the question mark next to user-defined command field. All question marks have further explanations. Seems quite obvious to me but maybe it isn't to others.

**Comment by cjrayance** [comment]
Found it, thank you very much. 

At first, I didn't hover over the mouse, I clicked on the quest mark. and nothing happened I thought it was a bug with my browser. Sorry for misunderstanding.

**Comment by rowrawer** [comment]
Subtitles can now be used with the built-in tool commands at the user's discretion as of v2.11.2 once it gets approved by Mozilla. I've also added a hint in the options menu in regard to the question mark functionality.
