### ISSUE TITLE
Request for a copy of the old .xpi file 

### ISSUE THREAD

**Issue by dhljet** [rowrawer/stream-detector#19]
Hi Rowrawer, I would like to request for a copy  by email (to dhljet@gmail.com) of the .xpi file for the older version of the plugin, HLS Stream Detector.  I am still using Firefox 52.xx, hence the request.  Thank you much.

**Comment by rowrawer** [comment]
I don't have it on hand, sorry - although maybe someone else could send it to you. I'd also generally advise against using an outdated browser if you can help it.

**Comment by dhljet** [comment]
Thanks for the quick reply!  I do need to use the old version.   Can anyone else out there email me a copy of the .xpi if you have one?   Thanks.

**Comment by davexnet** [comment]
All the old release are here, as they should be:
https://github.com/rowrawer/stream-detector/releases

**Comment by rowrawer** [comment]
Those only encompass the WebExtensions rewrite - earlier versions (v0.x) were uploaded to the Mozilla Addons repository only, and then all the pre-Quantum addons were deleted.

**Comment by davexnet** [comment]
I'm not sure what version I had in Firefox.  It automatically installed the latest and wasn't detecting and/or working properly.
Downloaded the 1.x version and that seemed to restore functionality. For now I have disabled automatic update.
I may test the latest version in another profile when I've got some time, but from what I saw of it, it still needs work
