### ISSUE TITLE
Use single quotation marks in cookies

### ISSUE THREAD

**Issue by DyeffersonAz** [rowrawer/stream-detector#20]
Using double quotation marks causes errors in windows 10 (SO I'm using at the moment).
This is an example:
![image](https://user-images.githubusercontent.com/16638560/86304248-b9a8b380-bbe4-11ea-905a-d0f2085d9bbd.png)

*quotation marks in cookies shown highlighted*

**P.S.:** After replacing these for single quotation marks it worked normally.

**EDIT:** I've used the streamlink command "copy to clipboard".

**Comment by rowrawer** [comment]
Good idea. If it doesn't invalidate the cookies, then it's a good preventative measure.

**Comment by rowrawer** [comment]
Implemented as of v2.1.2.

**Comment by DyeffersonAz** [comment]
It worked! Thank you!
