### ISSUE TITLE
Vimeo compatibility

### ISSUE THREAD

**Issue by 07416** [rowrawer/stream-detector#21]
The addon doesn't detect any playlist file with Vimeo streams, it seems. The menu also struggles to open at least on my system (Firefox 78.0.1 Windows 64-bit).

you can try any video from here for instance: https://vimeo.com/channels/staffpicks

**Comment by rowrawer** [comment]
Vimeo does not use any of the technologies supported by the addon (HLS, DASH, HDS, MSS), therefore it won't be detected by the addon. There's no real need to use the addon with such mainstream websites anyway, as they are supported by e.g. youtube-dl directly.

**Comment by 07416** [comment]
> 
> 
> Vimeo does not use any of the technologies supported by the addon (HLS, DASH, HDS, MSS), therefore it won't be detected by the addon. 

I see.

>There's no real need to use the addon with such mainstream websites anyway, as they are supported by e.g. youtube-dl directly.

I'm downloading content I've purchased from Vimeo and thought that giving the direct playlist file might be easier.

**Comment by 07416** [comment]
@rowrawer Could you exclude vimeo.com as the addon isn't compatible to avoid confusion?

**Comment by rowrawer** [comment]
>I'm downloading content I've purchased from Vimeo and thought that giving the direct playlist file might be easier.

That's also supported by youtube-dl, I think - admittedly I've only ever used it for YouTube Premium, but as far as I know the only additional thing you need to do one time is export the relevant cookies to a text file by using e.g. the cookies.txt addon and then supply them to youtube-dl.

>Could you exclude vimeo.com as the addon isn't compatible to avoid confusion?

Not really - I'll add a general note somewhere in the addon description/readme for the sake of clarity, but the supported technologies are already clearly denoted. Keeping up with the techniques used by particular websites would be a hassle.
