### ISSUE TITLE
Disabling Notifications Prevents URL/command from appearing

### ISSUE THREAD

**Issue by cornCobber** [rowrawer/stream-detector#23]
Setup:

Win10 build 1909
FF 79 64-bit
The Stream Detector 2.2.0

Thanks so much for this excellent tool! I found recently (I believe in 2.2.0 only - never seen this behavior before) that if you disable notifications from the Add-On menu (Options) that while a number will show up on the icon for TSD as if it detected one, when you click the icon, no URL appears to be available to copy.

I tried closing the tab, reopening, disabling TSD, re-enabling. Once notifications were turned back on (from Add-Ons, TSD, Options) I could not see any URL appear in the icon window.

**Comment by rowrawer** [comment]
Unfortunately I can't reproduce this - the URLs show up correctly for me with the same setup. Does the URL not show up at all in the all tabs/previous sessions sections?
