### ISSUE TITLE
referrer info / custom command

### ISSUE THREAD

**Issue by ysr23** [rowrawer/stream-detector#27]
Many thanks for your work on this - its the only plugin i have tried that actually finds the m3u8.

I have a question though - for my ffmpeg command i need the referrer, header and possibly cookie info - on this page:
https://addons.mozilla.org/en-GB/firefox/addon/hls-stream-detector/

there is mention that these attributes are available, however any aut-generated command doesn't seem to contain that info?

ffmpeg -i "https://thewebsite.net/out/u/FAPL200926BHAVMUN_5.m3u8" -c copy "FAPL200926BHAVMUN_5.ts"

i just get the m3u8 url ?

also, how do i create a custom command?

many thanks, again

**Comment by rowrawer** [comment]
If the "Include additional headers" checkbox is checked in the options menu of the addon, then these headers will be included, unless they are unavailable for whatever reason. As for custom commands, choose "User-defined command" from the "Copy stream URL as:" menu and create your command in the textbox below, including the available fields as necessary (listed upon hovering over the question mark).
