### ISSUE TITLE
Add an option to the streamlink copy feature to play the stream (--player=<playername>) instead of writing to file (-o <file>)

### ISSUE THREAD

**Issue by arcooke** [rowrawer/stream-detector#3]
Hi

Nice extension!  I am using it primarily with streamlink to watch web videos on my desktop.  When you select the streamlink option, the command it generates writes to file by default (`-o "file.ext"`)

https://github.com/rowrawer/stream-detector/blob/434a8052995802a278191d6f1768b8617f7a0af2/background.js#L255

streamlink is primarily intended to be used to stream directly to a desktop player.  With no options, it launches the default media player, and `--player=vlc` or `--player=mpv` let you choose a custom player.

In the Stream Detector settings, when choosing `streamlink` as the copy format.. I suggest adding a secondary setting to enable a toggle for "Output to file" or "Output to player".  I suppose a bonus suggestion would be to allow the user to choose a custom player from a list.. supported players are here https://streamlink.github.io/players.html

Thanks for reading

**Comment by rowrawer** [comment]
Good idea. Thanks for letting me know, this will be implemented in the next release (let me know if it works properly for you).

Choosing a custom player would be cool, but a bit too troublesome to maintain. The custom command option should suffice.
