### ISSUE TITLE
Stream URLs not draggable

### ISSUE THREAD

**Issue by realnc** [rowrawer/stream-detector#30]
It would be immensely useful if the extension would allow dragging the detected stream URLs so they can be dropped into a media player (like mpv or vlc). Right now, I have to click the stream "filename" so it gets copied to the clipboard,, then I have to open a text editor, then paste the URL in it, and then finally drag that into the media player.

**Comment by rowrawer** [comment]
Good idea, I've added this functionality.

**Comment by realnc** [comment]
Just updated and it works. Thank you!
