### ISSUE TITLE
Blank popup

### ISSUE THREAD

**Issue by DyeffersonAz** [rowrawer/stream-detector#31]
I'm using Firefox 83 and the extension is not working as expected. It is showing a blank popup when I click on it in the toolbar.
![image](https://user-images.githubusercontent.com/16638560/99887422-0ab45500-2c23-11eb-885e-7fe37b98de64.png)

Your extension is useful, thank you!

**Comment by rowrawer** [comment]
It works fine for me in 83. This might be a Firefox issue - I've had some addons stop working randomly and display blank options pages, for instance. Restarting the browser usually fixed it.

**Comment by DyeffersonAz** [comment]
I reset my browser by initialization and by task manager. Do you know why is this happening?

**Comment by rowrawer** [comment]
I have absolutely no clue.

**Comment by DyeffersonAz** [comment]
Hmm, so that is a problem to be solved. I don't know either. I'll try to restart the computer, in case of any result I'll be posting it here 😉

**Comment by rowrawer** [comment]
You could try reinstalling Firefox 82 for testing purposes. Or try making a new profile in Firefox and see what happens.

**Comment by ericlee4** [comment]
I ran into this issue today but I don't think it's directly related to the extension. The UI would load blank initially but after a few seconds the rest would load. I also noticed other UI elements were slow like opening new tabs/side view (tree style tabs), and other extensions popup menus (uMatrix). I tried safe mode and the UI slowness went away so I assumed it was an extension but running a fresh profile with `web-ext` against master didn't reproduce the issue. 

Maybe a memory leak or spending too much time pulling a large amount of data from the local storage API blocks across other extensions? Some sites are especially spammy with their HLS streams and I haven't restarted my machine in a few days so it was definitely possible that I had tens of thousands of unique stream URLs viewed. 

The `about:performance` and `about:memory` pages didn't reveal much but after disabled/re-enabling this extension the issue went away.

**Comment by rowrawer** [comment]
Yeah that might be an issue. Though I'm pretty sure local storage tops out at something like 5MB per addon. I don't really see any possible culprits for memory leaks in the code. I could try reducing the amount of data stored per entry but I really don't think that would cause significant slowdowns. Maybe I'll add a (adjustable) cap of max entries kept in local storage at a time.

**Comment by DyeffersonAz** [comment]
Well, in a new firefox profile it's working, but still not working on my own profile.

**Comment by rowrawer** [comment]
Might be related to this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1672139

**Comment by rowrawer** [comment]
This should hopefully be fixed in v2.10.6.
