### ISSUE TITLE
2.5.0 does not work for me, useragent sting /referer is missing in youtube-dl cmd - 2.4.1 still work !

### ISSUE THREAD

**Issue by deepblue2000** [rowrawer/stream-detector#32]
2.5.0 does not work for me, useragent sting is missing in youtube-dl cmd

I downgraded back to 2.4.1, youtube-dl is working again

2.4.1:
youtube-dl --no-part --restrict-filenames --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" --referer "https://xxxxx.com"

2.5.0:
youtube-dl --no-part --restrict-filenames "https://xxxxx.com"

**Comment by rowrawer** [comment]
It works just fine for me. User data gets reset when 2.5.0 is installed so make sure all the options are checked, maybe uncheck and check them again just to be sure, etc.

**Comment by rowrawer** [comment]
I have now pushed an update which should mitigate the issue. I was guessing so I've no clue if it'll work, but I'm hoping it will.
