### ISSUE TITLE
Add dark mode for options page

### ISSUE THREAD

**Issue by ericlee4** [rowrawer/stream-detector#33]
With `ui.systemUsesDarkTheme=1` the options pane still uses a light background. Here's the results from a quick look at how other extensions handle this:

## tree style tabs
Copy/pasted from mozilla source
https://github.com/piroor/treestyletab/blob/trunk/webextensions/resources/ui-color.css#L200
then imported and used with `prefers-color-scheme: dark`
https://github.com/piroor/treestyletab/blob/trunk/webextensions/options/options.css#L26

## multi-account containers
Hard-coded with same value from mozilla source
https://github.com/mozilla/multi-account-containers/blob/master/src/css/options.css#L19

## before -> after
![image](https://user-images.githubusercontent.com/36579598/105222716-dc6ecb00-5b28-11eb-9fe0-e162b31a0b68.png)

## diff
```
diff --git a/content/options.html b/content/options.html
index c0c80f0..ec0d665 100644
--- a/content/options.html
+++ b/content/options.html
@@ -4,10 +4,13 @@
        <head>
                <meta charset="utf-8" />
                <title>The Stream Detector</title>
+      <link rel="stylesheet" href="chrome://global/skin/in-content/common.css"/>
                <style>
                        body {
                                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto",
                                        "Oxygen", "Ubuntu", "Helvetica Neue", Arial, sans-serif;
+            color: var(--in-content-text-color);
+            background: var(--in-content-box-background);
                        }
                </style>
        </head>
```

Not sure if linking the browser's built-in stylesheet is recommended or not, haven't really looked into it. You should also note that pulling in their stylesheet does apply some other changes to borders/padding so that may need to be adjusted. I can submit a pull request too if you'd prefer checking out that way.

**Comment by rowrawer** [comment]
Thanks for your in-depth analysis. I've decided to hardcode the colors in the CSS, for now at least, as I remember browser styles causing issues on older versions of Firefox.
