### ISSUE TITLE
ffmpeg command generated / position additional cmps

### ISSUE THREAD

**Issue by zec-github** [rowrawer/stream-detector#36]
Dear dev, 1000x thanks for this wonderful idea and the released Firefox Add-on.

I would like to know if it is possible to have a placeholder where the additional command line parameters are placed. In my case (ffmpeg) I would like to add `-metadata comment="nice to have comment"`. This cmps must be placed before the output file or will fail.

Maybe you could use placeholders like this:

`{tool} {in parameters} {grabbed m3u8} {out parameters} {outfile}`

Example:
`ffmpeg -y -hide_banner -loglevel warning -stats -headers "Origin: demo.com\r\nReferer: demo.com" -user_agent "Mozilla..." -i "https://demo.com/demo.m3u8" -c copy   -metadata comment="video from demo.com" -metadata title="Demo Movie (2021)" "Demo Movie (2021).mp4"`

Maybe also add placeholders for the URL of the site where the m3u8 was grabbed for origin and maybe the title to use it for file name... 😉  Reaching for the stars... 😃

**Comment by rowrawer** [comment]
In your case I think it would be better to use the user-defined command instead of the additional parameters. I could add an origin URL field, though the referer field should work okay in the meantime. The title is not accessible in the requests/headers made by the addon, but I'll look into it.

**Comment by zecman** [comment]
Thanks for answering.

Custom command works great. I now use:
`ffmpeg -headers "Origin: https://demo.cx\r\nReferer: https://demo.cx\r\n" -i "%url%" -c copy -y -loglevel warning -stats -user_agent "%useragent%" -metadata comment="video from demo.cx" "DOWNLOAD.mp4" && chmod a+rwx ./DOWNLOAD.mp4`

Works like a charm.

But, I saw that using a variable twice (eg. %url% in the comment) did not work. Each variable can only be used once in the line.

Actually I do not need to have them multiple times.

I could to a translation to German if you want un return.

**Comment by rowrawer** [comment]
Good to hear you got it working in the end! If you want to translate the addon, then sure, feel free to do so. 


>But, I saw that using a variable twice (eg. %url% in the comment) did not work. Each variable can only be used once in the line.

This is a good point. I'll fix this for the next release.

**Comment by zec-github** [comment]
hey again. i forked, added de folder + .json and committed
tell me if you want something changed
