### ISSUE TITLE
I'd like to translate your addon into korean

### ISSUE THREAD

**Issue by ubless607** [rowrawer/stream-detector#39]
Hello, I'd like to translate your addon into korean.

I am a novice, so I need a little help.

1. What should I name the folder for korean? Is it 'ko' or 'kr'? 
2. What should I do to translate the README.md file?

**Comment by rowrawer** [comment]
Hi. Thanks for reaching out.

1. [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) says the code for Korean is ko - I would assume this is what Firefox uses.
2. The README.md file is a part of the GitHub repository and not the addon itself, so it's not really up for translation. You could theoretically translate the [AMO listing](https://addons.mozilla.org/firefox/addon/hls-stream-detector/) (short description on the top + the "About this extension" section) and e.g. paste the translation here, but then I might have to delete it in the future if I modify the description. That's up to you.

**Comment by ubless607** [comment]
Thanks for your answer. I thought that translating the README.md file into korean would help korean users get used to your addon. I just translated the messages.json file.
