### ISSUE TITLE
better output file naming option

### ISSUE THREAD

**Issue by ubless607** [rowrawer/stream-detector#41]
![rename](https://user-images.githubusercontent.com/5417257/108149222-b16e9b80-7115-11eb-8f17-110309c325c5.png)

Hello, I brought up an idea about output file naming.

Basically, stream-detector uses the name "playback.ts" or "index.ts" (something like that...). The problem is that these names are so common that if I download another video, ffmpeg says that there already exists the same filename.

I have 2 solutions.

First: Use the "source" name as filename. Add this option in the settings page. or some websites shows their video name in the html document. (e.g: `<div class = "tit">`)

Second: Clicking the filename, before copying the URL, the dialog box shows up (like the pic I posted above) and users can easily specify their filename as they want. The renamed "filename" can be added as the --output options.

Sorry for my bad explanation. Thank you.

**Comment by kls0e** [comment]
thanks a lot for this brilliant addon. +1 for %tabtitle% as variable for custom command.

**Comment by rowrawer** [comment]
Thanks for your suggestions. I think a dialog box would get annoying pretty quickly, but solution 1 + a `%tabtitle%` field sound good.

**Comment by ubless607** [comment]
What about adding both? Let users decide what they want.

Like @kls0e and @rowrawer mentioned, solution 1 + a `%tabtitle` is the default.
and the solution 2 is the alternative option. I prefer the second idea :)

**Comment by rowrawer** [comment]
For now, I will implement solution 1 in the next update. If I find a viable way of implementing a dialog box in the addon and find enough time in the future, I will add solution 2 as an option.

**Comment by rowrawer** [comment]
Solution 1 has been implemented in v2.6.4.
