### ISSUE TITLE
Help With Custom Command

### ISSUE THREAD

**Issue by UnitedDugout27** [rowrawer/stream-detector#44]
I am using the YouTube-DL command, but I need to add additional % to the command. I tired adding it myself with the custom command but I simply can not understand how to.

For example, I need 

--output "file.%(ext)s

to change to

--output "file.%%(ext)s

Can someone help me keep the Youthen-DL command but just add that extra % to it?

**Comment by mmshasan** [comment]
In popup.js find the following case section. Adding extra % before **%(ext)s** might work. make sure to make a backup copy before messing around.

```
case "youtubedl":
              if (filenamePref && e.tabData && e.tabData.title) code += ` --output "${outFilename}.%(ext)s"`;
              code += ` "${streamURL}"`;
              break;
```

**Comment by UnitedDugout27** [comment]
Where would popup.js be located? I searched my PC and did not find any file named that within firebox folders, which is the browser I use.

**Comment by rowrawer** [comment]
I'm not really sure what you're trying to do - if you only need to add one character, wouldn't it be easier to do a search & replace afterwards? I.e. search for %(ext)s and replace with %%(ext)s

**Comment by UnitedDugout27** [comment]
I want a one click method. I am downloading tons of videos and doing what you suggested is Monotonous. Also, if I did what you are suggesting, the cookies for that available session expire before I can successfully download video.

I would like to change the "Copy stream URL as" option to "user-defined command". Then when I copy a URL, it has the same format as the built in YouTube-DL command, but adds the additional text that I mentioned.

**Comment by rowrawer** [comment]
You could easily do that by selecting "copy all visible URLs", pasting them into Notepad or any text editor and selecting "replace all". Wouldn't take too long, I think. Otherwise you can rewrite the entire command from stratch in the user-defined command field, i.e. `youtube-dl %url% --output %filename%.%%(ext)s`.

**Comment by UnitedDugout27** [comment]
"youtube-dl %url% --output %filename%.%%(ext)s"

Thank you for your reply! That worked!!!
