### ISSUE TITLE
Add Support for N_m3u8DL-CLI

### ISSUE THREAD

**Issue by mmshasan** [rowrawer/stream-detector#47]
Hi,
Might it be possible to add support for N_m3u8DL-CLI which also another great video downloader? Thanks for your hard work.

https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by rowrawer** [comment]
I'll look into it. Thanks for letting me know about the tool.

**Comment by mmshasan** [comment]
Just checked 2.7.0 on Brave and it's look like this

[Screenshot](https://i.imgur.com/dzm4zs8.png)

**Comment by rowrawer** [comment]
I've replaced the crx file. Should work fine now. Although I would recommend using Firefox instead.

**Comment by mmshasan** [comment]
Thanks for your prompt response.
