### ISSUE TITLE
%cookie% in user-defined command?

### ISSUE THREAD

**Issue by goooglefc** [rowrawer/stream-detector#48]
For facebook videos that require login, 
If i type --http-cookie "%cookie%" in user-define commands, it provides nothing in output. 
What's the proper way to get %cookie% key in user-defined commands?
Thanks.

**Comment by rowrawer** [comment]
If there is nothing in the output, that means there was no cookie attached to that particular link. Unless there is one when using one of the built-in commands?

**Comment by goooglefc** [comment]
yes, there is cookie attached to the link.. Is there anything wrong with the syntax? Not getting any using the builtin commands as well.

**Comment by rowrawer** [comment]
If there are no cookies present when using the built-in commands either, that means there were no cookies included with that particular request/response for whatever reason. The addon makes use of what the browser provides.

When it comes to services like Facebook I would recommend e.g. using youtube-dl directly, with the --cookies command.
