### ISSUE TITLE
Automatically add date/time to file name

### ISSUE THREAD

**Issue by Mrnofish** [rowrawer/stream-detector#52]
Avoid conflicts and/or overwrite? prompts by having the option of automatically adding date/time to the output file name.

**Comment by rowrawer** [comment]
Sure, why not.

**Comment by rowrawer** [comment]
This is now available as of v2.7.1.

**Comment by Mrnofish** [comment]
Appreciated, thank you!

**Comment by Mrnofish** [comment]
Re-opening because the timestamp isn't working on Windows: the separator being used for the time is a colon, a reserved character.

Speaking of which, it would be useful to set the format for both date and time.

I'm often using the yy-mm-dd format for dates, as it basically sorts automatically. I imagine maybe some areas would prefer to switch 12h/24h time formats.

**Comment by Mrnofish** [comment]
PS: The slash character, used as a separator for the date, is also reserved.

**Comment by rowrawer** [comment]
The date is formatted according to your locale, so not every timestamp will contain these characters - though it should definitely be sanitized regardless, you're right. Implementing a custom format sounds like a pain, but maybe someday.

**Comment by rowrawer** [comment]
Fixed in v2.7.2.
