### ISSUE TITLE
Use tab title as filename option not working correctlly.

### ISSUE THREAD

**Issue by napgiver** [rowrawer/stream-detector#54]
The "--output" is inserted into the line for the "youtube-dl command", regardless of whether "Use tab title as filename" is checked or unchecked.

**Comment by rowrawer** [comment]
It is indeed. What is the issue?

**Comment by napgiver** [comment]
The issue, is when I uncheck the box so it's NOT added, It still gets added. I don't want it in the "youtube-dl command". As of right now, I have to remove it after I've pasted it into the batch file.

**Comment by rowrawer** [comment]
That's not really what that option was intended for. This was an intentional change to give the addon full control over the resulting filename after I implemented the "add timestamp to filename" option. I guess I could revert to the previous behavior in the next update.
