### ISSUE TITLE
Change default ffmpeg output from .ts to .mp4 ?

### ISSUE THREAD

**Issue by Mrnofish** [rowrawer/stream-detector#57]
The ffmpeg output command defaults to .ts, a format that isn't as widely recognized as .mp4 by other tools.

Since ffmpeg appears to support .mp4 as an output format without obvious drawbacks, I am suggesting .ts to be changed to .mp4, or another equally popular format.

**Comment by rowrawer** [comment]
TS is still the broadcasting standard, but I get what you're saying. I will probably implement this as an option.

**Comment by Mrnofish** [comment]
Thank you once again.

For the record, I'm totally not partial to mp4, it just appears all of the other tools default to it. Any other popular container would be great.

**Comment by rowrawer** [comment]
File extension us now selectable in the options in v2.7.2.
