### ISSUE TITLE
It doesn't detect FB or YT videos

### ISSUE THREAD

**Issue by Jimmy03** [rowrawer/stream-detector#6]
I was hoping it could, but doesn't for some reason.
I guess it's not needed for YT, but strange that FB videos aren't detected.
Using Firefox

**Comment by rowrawer** [comment]
They use different streaming solutions (or at least "non-standard"). For websites as popular as FB/YT you can just paste the link to the video straight into youtube-dl, e.g. "youtube-dl https://www.youtube.com/watch?v=dQw4w9WgXcQ"

**Comment by Jimmy03** [comment]
The problem is getting the direct link

**Comment by rowrawer** [comment]
Aren't there direct links to particular comments that you could plug into youtube-dl? I'm sure it can handle them in some way. Although I don't personally use Facebook, so I wouldn't really know.

**Comment by Jimmy03** [comment]
I think if you direct link to a comment it loads the whole comment thread which might have a bunch of other videos that you don't want.
