### ISSUE TITLE
VTT?

### ISSUE THREAD

**Issue by goooglefc** [rowrawer/stream-detector#60]
The addon is also detecting VTT which is a subtitle file I believe. 
Is there a way to turn this off?

![1](https://user-images.githubusercontent.com/31323637/112899991-447af800-90fc-11eb-84d7-d90d38e8a8ad.jpg)

**Comment by rowrawer** [comment]
No, that's intentional. I guess I could add yet another checkbox to the options menu.

**Comment by goooglefc** [comment]
I think so.

**Comment by rowrawer** [comment]
This is now available in v2.7.3.
