### ISSUE TITLE
usercmd.py

### ISSUE THREAD

**Issue by Littlesloths** [rowrawer/stream-detector#62]
Hi, I try to use usercmd.py to do my own command order because e.g. ffmpeg additional commandline parameter are placed at a wrong position in my context.
I created a batch file xyz.cmd instead to forward %url%, but the file is not launched. Also including the full path to the File: e.g. C:\test\xyz.cmd %url%
Is that how it should work?

**Comment by rowrawer** [comment]
I'm assuming you mean the user command field. How you launch files is not within the scope of the addon, that depends on you and your OS entirely. The user command simply replaces several fields in a string. So e.g. `ffmpeg -i %url% -c copy %tabtitle%.mp4`.

**Comment by Littlesloths** [comment]
well, originally I like to recode h264 to h265 on the fly to reduce space.
The parameters are
ffmpeg -user_agent "xyz" -referer "xyz“. -i %url% -c:v libx265 -tag:v hvc1 "File.ts" 
but additional parameters are inserted right after ffmpeg like this:
ffmpeg -c:v libx265 -tag:v hvc1 -user_agent "xyz“. -referer "xyz" -i %url% –c copy "File.ts"

unfortunaltelly ffmpeg does not accept that order, also -c copy is one -c too much

Therefore I tried to use a sript file or .cmd file to create the string on my own, but the method using usercmd.py seems not to work . I tried usercmd.cmd %url% to test, but the cmd file seems not to be executed at all (also with full path)

**Comment by rowrawer** [comment]
Wouldn't it make more sense for you to simply use this as your custom command? I don't see any reason to route this through a command/batch file, that sounds like a headache.

`ffmpeg -i %url% -c:v libx265 -tag:v hvc1 "File.ts"`

**Comment by Littlesloths** [comment]
well, yes, but as I said this option does not work as well...
is there a special path for the files?

see
Therefore I tried to use a script file or .cmd file to create the string on my own, but the method using usercmd.py seems not to work . I tried usercmd.cmd %url% to test, but the cmd file seems not to be executed at all (also with full path)

**Comment by rowrawer** [comment]
I'm not sure I fully understand. Any external scripts are not governed by the addon - if want to use them, you'll have to write them yourself (that includes figuring out how to make them work). If you've created a command file and it doesn't work, I can't tell you why that is - it has nothing to do with the addon. As stated previously, all the addon does is create a command. It does not install any additional files etc.

**Comment by Littlesloths** [comment]
ok, to make it simple: I like to use a custom command. therefore I create a file usercmd.cmd
In the settings of stream detector I add
usercmd.cmd %url%
Now, I would expect that usercmd.cmd is launched and %url% can be processed in the file.
Correct?
(but it seems not to work)

**Comment by rowrawer** [comment]
I still don't really get it, so let me put it this way: When you copy URLs with the user command option, is the `%url%` part replaced with the actual URL? If it is, then that's all the addon is supposed to do.

**Comment by Littlesloths** [comment]
ok, now I know the reason... the addon does not launch anything but copies it to the clipboard...
thank you
