### ISSUE TITLE
Feature Request: ability to copy url/command with a key bind instead of mouse click

### ISSUE THREAD

**Issue by ruifm** [rowrawer/stream-detector#63]
I really love this extension, now I couldn't leave without it but there is always one thing bugging me: I have to use the mouse to get what I want.

I have no js experience but it would be amazing if there would be a way to use it in a keyboard-only driven way.

**Comment by rowrawer** [comment]
I'll look into it. I think the best course of action would be to open the popup window with a key binding and then navigate the list with the keyboard as you would a website. Maybe a shortcut to copy the latest detected URL also.

**Comment by rowrawer** [comment]
Opening the popup is now available via keyboard shortcut in v2.7.4. The popup itself should be navigable like a regular website.
