### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by vampire55** [rowrawer/stream-detector#65]
Hello, I am not a developer or a programmer. I just joined github to report a bug (or rather a decoding issue, I think) that broke your otherwise excellent add-on. To put it simply, I generally use the add-on to get the m3u8 files to download videos from several sites. However, suddenly today it simply stopped working (that is, the link extracted by stream-detector didn't show any streams). After messing around with browsers I simply used the firefox web-developer tools and searched for the m3u8 link manually and, to my surprise it worked.
So there had to be something wrong with the link extracted by your add-on. So I checked the working link against the non-working link and that is the result:

Link extracted by web-developer tools:

https://xxxxxxx.prod.boltdns.xxx/manifest/v1/hls/v4/clear/4235717419001/2f7195b5-6b57-4880-8128-13e01827fa56/10s/master.m3u8?fastly_token=NjA3Mzk3YWJfMDRjMDczOGM0ZGU3MGE0ZDUyN2M2ZjkyZmE5NTViOTlmNzg1MjM1YTUxYzdiNzEwYTE1Y2YxMGU5NTQ0NjE5YQ==

Link extracted by stream-detector:

https://xxxxxxx.prod.boltdns.xxx/manifest/v1/hls/v4/clear/4235717419001/2f7195b5-6b57-4880-8128-13e01827fa56/10s/master.m3u8?fastly_token=NjA3Mzk3YWJfMDRjMDczOGM0ZGU3MGE0ZDUyN2M2ZjkyZmE5NTViOTlmNzg1MjM1YTUxYzdiNzEwYTE1Y2YxMGU5NTQ0NjE5YQ%253D%253D

If you're a good observer you surely already spotted where is the bug:  stream-detector substituted the last 2 characters "==" with their encoded alias "%253D%253D" and that prevents the link from working.

Could you please fix this little bug?? It shouldn't be too much of a problem.
Thanks for your attention and keep up the good works 

Regards,
MJ

**Comment by rowrawer** [comment]
This shouldn't really make much of a difference, most tools should be able to decode this without any issue. That being said, I'll roll back the change for the sake of compatibility.

**Comment by vampire55** [comment]
Thanks for your super-quick answer. I forgot to say, however, that I use the extracted links in programs such as youtube-dl-gui and fireDM because I'm not good at using command-line programs, and actually it does make a difference because the link above with the encoded characters simply doesn't work in these programs (that is, it doesn't find any streams). 

This is only to clarify that it's not only a matter of compatibility !

Thanks for your attention and regards,
MJ

**Comment by rowrawer** [comment]
That's good to know. Thanks for your thorough report.
