### ISSUE TITLE
Clicking the toolbar icon no longer clears the stream list

### ISSUE THREAD

**Issue by arcooke** [rowrawer/stream-detector#7]
For about a week now, the toolbar icon for Stream Detector no longer clears the list when clicked.  I have to use the right-click context menu option to clear it.

I noticed that the extension was updated about a week ago which seems in line with when the button quit working for me, but it could also be due to an update in FF Nightly.  I've not yet tried in other versions of FF.

Stream Detector 1.10.0
Firefox Nightly 77.0a1 -- if I get a chance later, I'll test in FF stable or beta.

**Comment by rowrawer** [comment]
As stated in the changelog, the toolbar button now copies the URL list by default. This can be changed in the options. Unless it doesn't work even then, in which case it's probably due to something being broken in the Nightly.

**Comment by arcooke** [comment]
Oh gotcha, I didn't think to check because I assumed it was a big. All is working in nightly. Thanks!  Closing
