### ISSUE TITLE
Support for mp4 files

### ISSUE THREAD

**Issue by gitpoduser33q** [rowrawer/stream-detector#70]
I love the addon btw but it would be more awesome if it had support for finding mp4 urls/streams.

**Comment by gitpoduser33q** [comment]
I added this bit of code and it was able to detect a majority of mp4 files.

`{
		ext: ["mp4"],
		ct: ["video/mp4"],
		type: "MPEG-4",
		category: "stream"
	},`

**Comment by rowrawer** [comment]
The aim of the addon is mainly to help with streaming protocols moreso than video files directly (as that could lead to an overload of entries) but I suppose it wouldn't hurt to try.

**Comment by gitpoduser33q** [comment]
Maybe a feature to enable mp4 support could fix the overload

**Comment by rowrawer** [comment]
This is now included in v2.8.0 with a checkbox to turn off direct file detection in the options menu.

As for Chrome, it works fine for me - but I don't really support the Chrome version of the addon in general. My proposed fix for any Chrome issues is to not use Chrome.
