### ISSUE TITLE
Inserting %(epoch)s instead of harcoded time in youtube-dl output filename template

### ISSUE THREAD

**Issue by barbashovtd** [rowrawer/stream-detector#71]
For now, default youtube-dl command  returns filename string with hadrcoded stream start time. It causes some problems in situations when stream often breaks: in terminal first that you want to do is "!!" to continue download stream, but filename stays the same and overwrites previous stream part. But to properly continue download you must re-copy link from extension.

**Comment by rowrawer** [comment]
Thanks for letting me know. I'll change this in the next version.

**Comment by rowrawer** [comment]
This has now been implemented in v2.8.0.
