### ISSUE TITLE
Problem after chrome update

### ISSUE THREAD

**Issue by goooglefc** [rowrawer/stream-detector#74]
After updating Chrome to its latest version, I am not able to see the stream list. 

I can still click on 'copy all visible Urls' and it copies fine but the individual streams are not showing.

working fine on Firefox.

**Comment by rowrawer** [comment]
I'll look into it.

**Comment by gh0stl4b** [comment]
I've found that for some reason if I toggle the `overflow: auto` on `#urlList` (Line 24 of popup.css) using Developer tools in Chrome the list shows back up and acts like normal until I reopen the plugin, so I'm guessing it's a rendering issue in Chrome.

**Comment by rowrawer** [comment]
I've replaced the crx file in the v2.8.0 release. Should now be working in Chrome.

**Comment by goooglefc** [comment]
Tested and working fine now. Thanks!
