### ISSUE TITLE
Plugin crashes Firefox at startup

### ISSUE THREAD

**Issue by mvezzelli** [rowrawer/stream-detector#76]
I have latest version of Firefox, 90.0b4 (64 bit) and latest version of stream-detector 2.8.0.
If the extension is enabled and I start Firefox, the browser crashes. I have to start in safe mode and disable extension.

**Comment by mvezzelli** [comment]
Tried beta 5 upgrade (90.0b5 64bit on Windows), still crash. It crashes the moment I try to enable the plugin. It's very weird. I have few plugins, I tried disable them all, still crash when I enable Stream Detector.
Can't switch back to stable cause I would lose the profile.

Mozilla crash dump says
mozilla::ipc::MessageChannel::Send | mozilla::ipc::IProtocol::ChannelSend | IPC_Message_Name=PBackgroundIDBCursor::Msg_Response

MOZ_CRASH(IPC message size is too large)

Dunno if this helps.

**Comment by rowrawer** [comment]
Can't really do much, as it works just fine for me. Even if it did crash, betas are not stable by definition, so it's not something I would care too much about. I'll worry about it when 90 is released as stable.

Have you tried using the --allow-downgrade command line switch to go back to 89?

**Comment by mvezzelli** [comment]
I tried downgrading to 89 with your suggested parameter. It still crashes on firefox 89!!!
That's so weird.

The funny part: I uninstalled the plugin, restarted firefox, reinstalled the plugin. Now works.
Could be something related to plugin configuration?

**Comment by mvezzelli** [comment]
Thanks for the help! Is there a place where I can make donations? This plugin is really cool.

**Comment by rowrawer** [comment]
Not right now, as I'm maintaining the addon in my free time for my own use - but maybe in the future. Thank you for the offer!

**Comment by mvezzelli** [comment]
I'll keep an eye around then. Thanks for the excellent work.
