### ISSUE TITLE
is it wwork for udemy widevine-l3-decryptor?

### ISSUE THREAD

**Issue by mahdisky** [rowrawer/stream-detector#77]
hi
is it get udemy video widevine-l3-decryptor?
key and keyid?

**Comment by rowrawer** [comment]
No, the aim of the addon is not intended to circumvent any DRM. Although it's an avenue worth considering in the future, depending on the legality.

**Comment by mahdisky** [comment]
can you help me ?
i need key and keyid

**Comment by rowrawer** [comment]
No, sorry.
