### ISSUE TITLE
Option to blacklist specific sites

### ISSUE THREAD

**Issue by goooglefc** [rowrawer/stream-detector#79]
Would be nice to have an option to blacklist certain websites.
Whenever I am browsing on twitter.com, the addon just goes mental.

**Comment by rowrawer** [comment]
Good idea, I'll try to implement this.

**Comment by dinjojo** [comment]
+1 for this

**Comment by rowrawer** [comment]
The blacklist is now available as of v2.8.1. Let me know if it works.

**Comment by goooglefc** [comment]
> The blacklist is now available as of v2.8.1. Let me know if it works.

I have only tested on Twitter so far.
works fine on Firefox using just 'twitter' in the blacklist column.
Tested on chrome as well and seems to work there although I had to blacklist https://video.twimg.com for it to work on Chrome.

**Comment by rowrawer** [comment]
Thanks for your feedback. Looks like Chrome handles things differently, which is no surprise at this point. I've now updated the crx file in the releases tab, it should work the same way as in Firefox.

**Comment by goooglefc** [comment]
Thanks, yes it works now on chrome with the keyword.

**Comment by rowrawer** [comment]
Great, thanks for testing.
