### ISSUE TITLE
Limit stream detection to active tab

### ISSUE THREAD

**Issue by pokus1599** [rowrawer/stream-detector#8]
Hi,

It's possible to limit stream detection only to active tab? Because when I have opened more tabs with video it detects many stream and is impossible to detect which one is the one I want to download.

BTW. Great plugin thank you.

**Comment by rowrawer** [comment]
Yep, it's on the to-do list, as can be seen in the readme of the repo. At some point I hope to implement per-tab buttons/lists.

**Comment by rowrawer** [comment]
This is now available as of [v2.0.0](https://github.com/rowrawer/stream-detector/releases/tag/v2.0.0).
