### ISSUE TITLE
Sluggishness & flashing panel

### ISSUE THREAD

**Issue by Mrnofish** [rowrawer/stream-detector#80]
For quite some time now, I've been experiencing general sluggishness of TSD. In some occasions, the panel flashes, alternating between showing links and not. Sometimes it's fast enough that it looks like a flash, other times it's slower and the mid part of the panel, where the links should be, is missing.

This happens even after clearing the link list.

When it does the flashing thing, getting to operate the extension can be a challenge, as the clicks are seemingly not registering, so e.g. switching it on or off, or clearing the list, becomes an exercise in spamming, hoping that one click registers.

I'm using Firefox, currently 91.0 (64-bit) but this has been happening for a while, I'd say at least 89 and possibly earlier than that.

Is it just me?

**Comment by rowrawer** [comment]
This should hopefully be fixed in v2.10.6.
