### ISSUE TITLE
Copy All Visible URLs missing line breaks between commands.

### ISSUE THREAD

**Issue by AllThisThen** [rowrawer/stream-detector#82]
I first noticed this going from 2.6.4 to 2.7.0.
Great extension, btw. Learning to use it is teaching me some cool tools.

**Comment by rowrawer** [comment]
Thanks for letting me know. It works just fine for me though (every command is in a new line). What are your specs?

**Comment by AllThisThen** [comment]
Firefox 91.0.2 64-bit, Windows 8.1 Pro 64-bit.

**Comment by rowrawer** [comment]
Should be working fine, although ancient versions of Windows might have their quirks. If anyone else is also having this issue, let me know.

**Comment by AllThisThen** [comment]
I was mistaken earlier. 2.7.0 is fine. 2.7.1 is where the problem starts for me.

**Comment by rowrawer** [comment]
No idea if this still affects you, but I've finally implemented a possible fix.

**Comment by AllThisThen** [comment]
That fixed it! Extension is now at 100% in everything.

**Comment by rowrawer** [comment]
Wow, that worked? Great to hear, thanks.

**Comment by AllThisThen** [comment]
It was such a weird thing. I was looking at the code changes between when it worked and broke and couldn't see any difference at all with the relevant lines.

**Comment by rowrawer** [comment]
I'm assuming it's because 2.7.1 onwards uses the Clipboard API to copy the URLs whereas previous versions used `execCommand("copy")` by default. Looks like the latter modifies line endings depending on the OS and the former leaves them as-is.
