### ISSUE TITLE
.json/Base64 support

### ISSUE THREAD

**Issue by neabb** [rowrawer/stream-detector#84]
Hello,

Is it going to be tough to include .json/base64 support?
For example, this url (may be expired):

https://68vod-adaptive.akamaized.net/exp=1632492176~acl=%2F466ce9ed-184f-40d2-bc87-9bf3357b7e63%2F%2A~hmac=ecf231e9c9553ed215f57db77032ec6a98d750b530d5007c21512c70706733ec/466ce9ed-184f-40d2-bc87-9bf3357b7e63/sep/video/59ab041d,223b932c,efa23793,12478d43,8bd887c4/master.json?base64_init=1

is actually an .mpd file once the end section 'master.json?base64_init=1' becomes 'master.mpd'
After renaming, the file can easily be downloaded with youtube-dl.

**Comment by rowrawer** [comment]
Thanks for letting me know. These JSON files are now being detected as DASH streams in v2.8.4.
