### ISSUE TITLE
Firefox 93.0 (Windows 64-bit) crashes to desktop with this extension enabled

### ISSUE THREAD

**Issue by go2tom42** [rowrawer/stream-detector#85]
Title say it all

Firefox's lasted update causes it to crash to desktop if this extension is enabled

**Comment by AllThisThen** [comment]
Doesn't crash with that setup on mine. Crashes when? Upon opening Firefox (default homepage of about:newtab) ?

**Comment by rowrawer** [comment]
I've made some attempts to mitigate this in v2.8.4. Let me know if anything changed.

**Comment by rpgrca** [comment]
Yes, I confirm 2.8.5 (the one I got from the addon page) fixed the issue for me, thanks.

**Comment by rowrawer** [comment]
That's great to hear, thanks for confirming. @ailieff is it better for you as well?

**Comment by ailieff** [comment]
> That's great to hear, thanks for confirming. @ailieff is it better for you as well?

Confirm, its OK now! Thanks for fixing!

**Comment by rowrawer** [comment]
Great, thanks.

**Comment by rpgrca** [comment]
Unfortunately it started crashing again, version 2.9.0 on Firefox 95.0.1 (Ubuntu 21.10 64 bits). I got up this morning, Firefox told me that it had to do one small thing, so I restarted the browser and kept crashing until I disabled this extension. Not sure if you want a new report or reopen this one, hoping you read this comment.

**Comment by rowrawer** [comment]
Unfortunately at this point I've no clue what could be causing the crashes. Something's broken somewhere.

**Comment by ailieff** [comment]
I can confirm it started crashing again with 95.0.2 for me, too. Is there something that we can do to help you debug this?

**Comment by rowrawer** [comment]
I don't think so, as I've no clue what the root cause is. I'll try testing stuff out when I have some free time, although I don't have as much free time as I used to. It would be nice if someone more experienced chimed in or offered a pull request, but until then I'll keep guessing and maybe eventually it'll work as intended.

**Comment by rowrawer** [comment]
Let me know if the crashes are still occuring as of v2.10.6 onward.
