### ISSUE TITLE
Detection notification doesn't work at 2.8.4. update

### ISSUE THREAD

**Issue by DYTM** [rowrawer/stream-detector#89]
The detection notification didn't work after the 2.8.4 update. Please check. 😥

**Comment by rowrawer** [comment]
You're right, I've accidentally reversed the checkboxes. I'll fix this later today.

**Comment by rowrawer** [comment]
This has now been fixed in v2.8.5.

**Comment by DYTM** [comment]
> 
> 
> This has now been fixed in v2.8.5.

Thank you so much!
