### ISSUE TITLE
Lists stream parts instead of m38u + does show only old window links

### ISSUE THREAD

**Issue by Littlesloths** [rowrawer/stream-detector#93]
Hello, since 2.8.4 it is not really working anymore for e.g. Chaturbate. 
Links are days old and it did list all individual stream parts + the playlists... that ends up on hundredth of entries... hard to find the m38u if not impossible as stream parts update quite often...

**Comment by rowrawer** [comment]
Make sure "ignore direct links" is checked in the menu if you want to only capture stream links. If it doesn't work at all, try the "reset all settings" button which will delete all data and possibly fix the problem.

**Comment by rowrawer** [comment]
Type "master" in the filter, I guess? Or just go through the list and check manually.

**Comment by Mdferreira** [comment]
Sorry! I don't know how to use it very well. but it was working fine a few
days ago. i used it together with m3u8 downloader but it doesnt work now.
forgive me for my ignorance. thanks again!

Em seg., 6 de dez. de 2021 às 13:37, rowrawer ***@***.***>
escreveu:

**Comment by rowrawer** [comment]
Maybe the website changed their streaming solution or there has been some kind of bug in the addon. Try resetting the settings from the options menu.
