### ISSUE TITLE
[Firefox] Clear URL list not working

### ISSUE THREAD

**Issue by nicolaasjan** [rowrawer/stream-detector#95]
Firefox 94.0.2
Linux

When I click on "Clear this URL list", nothing happens...

It only gets cleared after uninstalling and reinstalling.

**Comment by rowrawer** [comment]
It works fine for me - have you tried the reset settings button in the options?

**Comment by nicolaasjan** [comment]
> It works fine for me - have you tried the reset settings button in the options?

No, I will try that when I encounter it again. Thanks.

Do you have any idea what could have caused this?

**Comment by rowrawer** [comment]
No, no clue, unfortunately.

**Comment by nicolaasjan** [comment]
After having reset the options, it now behaves as it should. :)
