### ISSUE TITLE
stream detector menu freezing

### ISSUE THREAD

**Issue by DYTM** [rowrawer/stream-detector#96]
Find about 30~40 same m3u8 addresses through refresh on the same site. 
Then the m3u8 address is no longer added, the m3u8 address is not copied, and the m3u8 list is not initialized. The stream detector menu will freezing.

So every time I did that for about a month, I installed the stream detector again.
In the end, I'm temporarily using the version before Oct when there was no freezing.
Is there a solution?

**Comment by rowrawer** [comment]
It works fine for me. I was hoping v2.9.0 would fix any possible slowdowns/freezes - I can't really pinpoint them because they don't happen to me.

**Comment by DYTM** [comment]
> 
Okay. I'll try using the new version. 
Thank you for answer!
