### ISSUE TITLE
Please provide extractor for hopin.com

### ISSUE THREAD

**Issue by sgargbugreporter** [rowrawer/stream-detector#98]
I wanted to download a replay of a training hosted at hopin.com - however, the stream detector is unable to detect the stream.

I can share the URL  privately as it embeds and authentication token.

Thanks

**Comment by rowrawer** [comment]
The aim of the addon is to be as universal as possible - individual extractors are more in the vein of e.g. youtube-dl (or its more up-to-date forks like yt-dlp). It's possible that the website uses a proprietary streaming solution which is outside of the scope of the addon. If the token doesn't expire, feel free to send me the URL to my GitHub email and I'll check it out when I have some time.
